"""Fail-before check: each mutant breaks one decided rule and must be killed by the tests named for
it; the restored tree must pass. Run from the repo root:  python tools/mutants.py [slice]

A mutant counts as killed only when a named test appears as a failure in the JUnit XML, never on a
bare non-zero exit (a build that did not run would otherwise look like a kill).
"""
import glob
import os
import re
import shutil
import subprocess
import sys

GRADLEW = os.path.abspath("gradlew.bat" if os.name == "nt" else "gradlew")
MERGE = "core/src/commonMain/kotlin/com/factotum/core/sync/Merge.kt"
OPEN = "data/src/jvmCommon/kotlin/com/factotum/data/OpenDatabase.kt"
FOLDER = "data/src/commonMain/kotlin/com/factotum/data/sync/FolderSync.kt"
STAGED = "data/src/commonMain/kotlin/com/factotum/data/sync/StagedStore.kt"
CODEC = "data/src/commonMain/kotlin/com/factotum/data/sync/Records.kt"
TRIGGERS = "data/src/commonMain/kotlin/com/factotum/data/SchemaTriggers.kt"
REPO = "data/src/commonMain/kotlin/com/factotum/data/item/ItemRepository.kt"
ITEMDAO = "data/src/commonMain/kotlin/com/factotum/data/item/ItemDao.kt"
WRITES = "data/src/commonMain/kotlin/com/factotum/data/LocalWrites.kt"
REMREPO = "data/src/commonMain/kotlin/com/factotum/data/reminder/ReminderRepository.kt"
REMDAO = "data/src/commonMain/kotlin/com/factotum/data/reminder/ReminderDao.kt"
RRULE = "core/src/commonMain/kotlin/com/factotum/core/recurrence/RRule.kt"
RECUR = "core/src/commonMain/kotlin/com/factotum/core/recurrence/Recurrence.kt"
CRON = "core/src/commonMain/kotlin/com/factotum/core/recurrence/Cron.kt"
EDITS = "core/src/commonMain/kotlin/com/factotum/core/recurrence/OccurrenceEdits.kt"
OCCREPO = "data/src/commonMain/kotlin/com/factotum/data/item/OccurrenceRepository.kt"
PRESENCE = "core/src/commonMain/kotlin/com/factotum/core/habit/HabitPresence.kt"
HABITS = "data/src/commonMain/kotlin/com/factotum/data/item/HabitRepository.kt"
TRACKERS = "data/src/commonMain/kotlin/com/factotum/data/tracker/TrackerRepository.kt"
PLANNER = "core/src/commonMain/kotlin/com/factotum/core/plan/Planner.kt"
DATABASE = "data/src/commonMain/kotlin/com/factotum/data/FactotumDatabase.kt"
EDITCODEC = "data/src/commonMain/kotlin/com/factotum/data/item/OccurrenceEditTable.kt"
TOTALS = "core/src/commonMain/kotlin/com/factotum/core/time/TimeTotals.kt"
TIMEREPO = "data/src/commonMain/kotlin/com/factotum/data/time/TimeRepository.kt"
TIMESPAN = "data/src/commonMain/kotlin/com/factotum/data/time/TimeSpan.kt"
ACTIVITIES = "data/src/commonMain/kotlin/com/factotum/data/time/ActivityRepository.kt"
LABELKEY = "core/src/commonMain/kotlin/com/factotum/core/label/Labels.kt"
LABELS = "data/src/commonMain/kotlin/com/factotum/data/label/LabelRepository.kt"
REGISTRY = "core/src/commonMain/kotlin/com/factotum/core/settings/Settings.kt"
SETTINGS = "data/src/commonMain/kotlin/com/factotum/data/settings/SettingsRepository.kt"
STORES = "data/src/commonMain/kotlin/com/factotum/data/settings/SettingStores.kt"
SEARCHINDEX = "data/src/commonMain/kotlin/com/factotum/data/search/SearchIndex.kt"
SEARCH = "data/src/commonMain/kotlin/com/factotum/data/search/SearchRepository.kt"
SCALES = "core/src/commonMain/kotlin/com/factotum/core/checkin/CheckIns.kt"
CHECKINS = "data/src/commonMain/kotlin/com/factotum/data/checkin/CheckInRepository.kt"
CHECKINDAO = "data/src/commonMain/kotlin/com/factotum/data/checkin/CheckIn.kt"
PAGES = "data/src/commonMain/kotlin/com/factotum/data/page/PageRepository.kt"
PAGE = "data/src/commonMain/kotlin/com/factotum/data/page/Page.kt"
DBS = "data/src/commonMain/kotlin/com/factotum/data/page/DatabaseRepository.kt"
CANVAS = "data/src/commonMain/kotlin/com/factotum/data/page/CanvasRepository.kt"
JOURNAL = "data/src/commonMain/kotlin/com/factotum/data/page/JournalRepository.kt"
RELS = "data/src/commonMain/kotlin/com/factotum/data/page/RelationRepository.kt"
TEMPL = "data/src/commonMain/kotlin/com/factotum/data/page/TemplateRepository.kt"
FORMULA = "core/src/commonMain/kotlin/com/factotum/core/formula/Formula.kt"
CHK = "data/src/commonMain/kotlin/com/factotum/data/checklist/ChecklistRepository.kt"
CHART = "data/src/commonMain/kotlin/com/factotum/data/chart/ChartRepository.kt"
CHARTS = "core/src/commonMain/kotlin/com/factotum/core/chart/Charts.kt"

# slice -> [(name, file, old, new, test task, tests that must fail)]
SLICES = {
    "01": [
        ("no ask (hybrid, not hybrid+)", MERGE, "if (mine.stamp != base && mine.values != theirs.values && theirs.settles",
         "if (false && mine.values != theirs.values && theirs.settles", ":core:desktopTest", {"mnemoSameTimeShown", "mnemoDeleteVsEditShown", "chronicleTieConverges"}),
        ("purge ignored on import", MERGE, "if (incoming.newest <= purge) continue", "if (false) continue",
         ":core:desktopTest", {"tendrilPurgeHolds"}),
        ("answers do not settle", MERGE, " && theirs.settles != mine.stamp", "",
         ":core:desktopTest", {"keepMineWinsEverywhere"}),
        ("a version no newer than the base is merged", MERGE, "            if (base != null && theirs.stamp <= base) continue\n", "",
         ":core:desktopTest", {"aReplayedOldVersionIsNotAskedAbout"}),
        ("an older replay replaces the pending question", MERGE, "if ((store.asked(local.id, name)?.stamp ?: theirs.stamp) <= theirs.stamp) ", "",
         ":core:desktopTest", {"aPendingQuestionIsNotReplacedByAnOlderReplay"}),
        ("Room's leaked connection kept open", OPEN, "            tracked.closeAll()\n", "",
         ":data:desktopTest", {"aDatabaseCorruptPastItsSchemaPageIsSetAsideToo"}),
    ],
    "13": [
        ("conflict copies not read", FOLDER, "val copy = FolderLayout.isConflictCopy(name)", "val copy = false",
         ":data:desktopTest", {"aClonedDeviceIdsClashIsMergedAndTheCopyRemoved"}),
        ("own clash not re-read", FOLDER, "val shared = owner == device && names.any(FolderLayout::isConflictCopy)",
         "val shared = false", ":data:desktopTest", {"aClonedDeviceIdsClashIsMergedAndTheCopyRemoved"}),
        ("log never compacted", FOLDER, "if (held.size >= snapshotEvery) {", "if (false) {",
         ":data:desktopTest", {"androidFiles1y_aYearKeepsEachDeviceToItsSegmentsAndOneSnapshot", "aPurgeReachesAPeerAndOutlivesCompaction"}),
        ("unfinished last line read", FOLDER, "    return lines\n}", "    if (start < bytes.size) lines += Line(bytes.decodeToString(start, bytes.size), bytes.size)\n    return lines\n}",
         ":data:desktopTest", {"aLineStillBeingWrittenWaitsForItsNewline", "onlyNewlineTerminatedLinesAreRead"}),
        ("positions kept when the tables change", FOLDER, "        dao.clearReads()\n        dao.saveKnownTables", "        dao.saveKnownTables",
         ":data:desktopTest", {"aLineForATableThisVersionLacksIsReadAgainOnceItHasIt"}),
        ("one transaction per file, not per chunk", FOLDER, "lines.chunked(MERGE_LINES)", "listOf(lines).filter { it.isNotEmpty() }",
         ":data:desktopTest", {"aBigFileIsMergedInChunksEachWithItsReadPosition"}),
        ("purges not exported", FOLDER, " ?: purges[id]?.let { PurgeRecord(id, it) }", "",
         ":data:desktopTest", {"aPurgeReachesAPeerThroughTheLog"}),
        ("unchanged files read again", FOLDER, "if (folder.size(path) == from) continue", "if (false) continue",
         ":data:desktopTest", {"aPeerFileIsReadOnlyWhenItHasGrown"}),
        ("Long and Double read alike", CODEC, "p.booleanOrNull ?: p.longOrNull ?: p.double", "p.booleanOrNull ?: p.double",
         ":data:desktopTest", {"aRowReadsBackWithEveryValueItsOwnType"}),
        ("a refused line stops the import", FOLDER, "                if (!isConstraintViolation(e)) throw e\n                // A backstop", "                throw e\n                // A backstop",
         ":data:desktopTest", {"aRowThatBreaksItsKindsRulesIsDroppedNotKeptWaiting"}),
        ("a line naming a purged parent waits forever", FOLDER, "                absent.any { it in purged } -> dropped += line.first\n", "",
         ":data:desktopTest", {"aSubtaskWhoseParentWasPurgedIsDroppedNotKeptWaiting"}),
        ("waiting lines never retried", FOLDER, "report + retryWaiting()", "report",
         ":data:desktopTest", {"aSubtaskThatArrivesBeforeItsParentWaitsForIt"}),
        ("a row that does not fit is merged", FOLDER, "tables[it.row.table]?.fits(it.row) == true", "it.row.table in tables",
         ":data:desktopTest", {"aRowThatDoesNotFitItsTableIsSkipped"}),
    ],
    "02": [
        ("kind rules dropped", TRIGGERS, '        ITEM to itemRules,\n', "",
         ":data:desktopTest", {"sharedEventHasNoTaskState_theDatabaseRefusesIt", "theKindRulesHoldAfterAReopen"}),
        ("completion status unchecked", TRIGGERS, '        COMPLETION to "NEW.status IN (\'DONE\', \'SKIPPED\')",\n', "",
         ":data:desktopTest", {"tendrilCompletionLog_eachOccurrenceKeepsItsOutcomeAndNoOtherStatusIsTaken"}),
        ("writes not queued for export", TRIGGERS, "for (table in SYNCED_TABLES)", "for (table in emptyList<String>())",
         ":data:desktopTest", {"stRetiredLoser_aWipedDevicesChangeSurvives", "aVersionOutlivesTheLossOfItsAuthorsFiles"}),
        ("a deleted parent keeps its subtasks", REPO, "listOf(id) + dao.liveChildren(id)", "listOf(id)",
         ":data:desktopTest", {"tendrilSubtaskCascade_aDeletedParentTakesItsSubtasks"}),
        ("rescheduling undeletes", REPO, ' - "deleted_at")', ")",
         ":data:desktopTest", {"rescheduleLeavesADeletedItemDeleted"}),
        ("a deleted row keeps its merge state", TRIGGERS, "DELETE FROM sync_base WHERE id = OLD.id; DELETE FROM sync_ask WHERE id = OLD.id;", "",
         ":data:desktopTest", {"aPurgedParentTakesItsSubtasksPendingQuestionWithIt"}),
        ("the clock is not saved with a write", WRITES, "                sync.saveClock(clock)\n", "",
         ":data:desktopTest", {"eachWriteSavesTheClockWithIt"}),
    ],
    "03": [
        ("alert settings unchecked", TRIGGERS, "        REMINDER to reminderRules,\n", "",
         ":data:desktopTest", {"chronicleAlertSettings_storedPerReminderAndUnknownValuesRefused"}),
        ("a standalone reminder without a time", TRIGGERS, "            AND (NEW.kind <> 'REMINDER' OR (NEW.start_date IS NOT NULL AND NEW.start_time IS NOT NULL))\n", "",
         ":data:desktopTest", {"aStandaloneReminderNeedsATime"}),
        ("a done item's reminder still fires", REMDAO, " +\n            \"AND (i.status IS NULL OR i.status = 'PENDING')\"", "",
         ":data:desktopTest", {"tendrilQuietWhenDone_aDoneTasksReminderNoLongerFires", "mnemoStandaloneDone_theRowStaysAndStopsFiring"}),
        ("a deleted item's reminder still fires", REMDAO, "AND i.deleted_at IS NULL AND t.deleted_at", "AND t.deleted_at",
         ":data:desktopTest", {"tendrilCascade_aDeletedTaskSilencesItsReminderAndAPurgedOneRemovesIt"}),
        ("a deleted reminder still fires", REMDAO, "\"WHERE r.deleted_at IS NULL AND ", "\"WHERE ",
         ":data:desktopTest", {"aDeletedReminderNoLongerFires"}),
        ("the anchor is ignored", REMREPO, "private val anchor = s.anchorTime?.let(LocalTime::parse) ?: MIDNIGHT", "private val anchor = MIDNIGHT",
         ":data:desktopTest", {"tendrilAnchorDateOnly_theDayBeforeAtNine"}),
        ("a snooze is ignored", REMREPO, "return listOfNotNull(snoozed, first(after, skip = snoozedFrom)).minOrNull()", "return first(after, skip = snoozedFrom)",
         ":data:desktopTest", {"aSnoozeMovesTheFiringAndLeavesTheItemsTimeAlone"}),
        ("a snooze outlives the firing it snoozed", REMREPO, "snoozedFrom != null && isDue(snoozedFrom)", "snoozedFrom != null",
         ":data:desktopTest", {"aSnoozeFromBeforeARescheduleNoLongerApplies", "aRescheduleThatDoesNotPassTheSnoozeStillMovesTheFiring", "aRetimedReminderDropsItsSnooze"}),
        ("standalone reminders crowd the day", ITEMDAO, "OR :showReminders)", "OR :showReminders OR 1)",
         ":data:desktopTest", {"sharedTimelineUnchanged_standaloneRemindersShowOnlyWhenAsked"}),
        ("a reminder on an undated item is taken", REMREPO, "require(item.startDate != null && ", "require(",
         ":data:desktopTest", {"aReminderOnAnItemWithNoDateIsRefused"}),
        ("a reminder on a deleted item is taken", REMREPO, " && item.deletedAt == null)", ")",
         ":data:desktopTest", {"aReminderOnADeletedItemIsRefused"}),
        ("an item with reminders loses its date", REPO, "require(start != null || reminders.remindersOf(id).isEmpty())", "require(true)",
         ":data:desktopTest", {"anItemWithRemindersKeepsItsStartDate"}),
        ("a standalone reminder's item outlives its last reminder", REMREPO, "if (standalone && last) listOf(itemId) else emptyList()", "emptyList()",
         ":data:desktopTest", {"deletingAStandaloneRemindersOnlyReminderDeletesItsItem"}),
        ("keep both leaves the copy without reminders", REPO, "reminders.remindersOf(id).forEach { copied[it.id] = newId() }", "Unit",
         ":data:desktopTest", {"keepingBothTimesOfAStandaloneReminderKeepsBothFiring"}),
    ],
    "04": [
        ("COUNT counted from the window", RRULE, "var period = if (count == null) firstPeriodNear(start, from) else 0L", "var period = firstPeriodNear(start, from)",
         ":core:desktopTest", {"countCountsFromTheStartEvenForALaterWindow"}),
        ("BYSETPOS ignored", RRULE, "    if (bySetPos.isEmpty()) return times\n", "    return times\n",
         ":core:desktopTest", {"bySetPosPicksWithinEachPeriod"}),
        ("an unknown part is ignored", RRULE, "if (name !in KNOWN || name in parts) return null", "if (name in parts) return null",
         ":core:desktopTest", {"aRuleWithAPartTheExpanderLacksIsRefusedNotGuessed"}),
        ("a year begins at the start's month", RRULE, "LocalDateTime(LocalDate(start.date.year, 1, 1).plus(step, DateTimeUnit.YEAR), MIDNIGHT)",
         "LocalDateTime(firstOfMonth(start.date).plus(step * 12, DateTimeUnit.MONTH), MIDNIGHT)",
         ":core:desktopTest", {"aYearlyRuleKeepsItsLastYearsEarlierMonths"}),
        ("cron's day OR weekday read as AND", CRON, "-> Recurrence.RuleSet(listOf(byMonthDay, byWeekday))", "-> Recurrence.Rule(byMonthDay.copy(byDay = byWeekday.byDay))",
         ":core:desktopTest", {"theNineFixedRulesGiveTheOwnerAppsOccurrences"}),
        ("draws seeded without the item", RECUR, 'kind: String) = "$itemId|$date|$kind"', 'kind: String) = "$date|$kind"',
         ":core:desktopTest", {"chronicleRandomDays_gapsOfTwoToFourDaysAtTheSameTimeTheSameOnEveryDevice"}),
        ("recurrence rules dropped", TRIGGERS, "        AND $recurrenceRules\n", "",
         ":data:desktopTest", {"eachKindKeepsToItsOwnColumns"}),
        ("rescheduling drops the recurrence", REPO, 'schedule(start, at, endDate, endTime, due) - "deleted_at")', 'schedule(start, at, endDate, endTime, due) - "deleted_at" + recurrenceValues(null))',
         ":data:desktopTest", {"reschedulingKeepsTheRecurrenceAndMovesItsStart"}),
        ("a resolved occurrence still fires", REMREPO, ".filter { (it.original ?: it.at) !in resolved && !habit.paused(it, timed(it)) }", ".filter { !habit.paused(it, timed(it)) }",
         ":data:desktopTest", {"aResolvedOccurrenceDoesNotFire"}),
        ("a whole-day repeat fires at its occurrence's midnight", REMREPO, "if (timed(o)) o.at.time else blockStart(o) ?: anchor", "o.at.time",
         ":data:desktopTest", {"aWholeDayRepeatingTaskFiresAtTheReminderAnchor"}),
        ("a whole-day rule's own times are ignored", EDITS, " || inForceOn(o.original?.date ?: o.at.date, edits)?.setsTimes == true", "",
         ":data:desktopTest", {"aWholeDayItemWhoseRuleSetsTimesFiresAtThem"}),
        ("one unreadable rule silences every reminder", REMREPO, "        } catch (_: IllegalArgumentException) {\n            return null\n", "        } catch (_: IllegalArgumentException) {\n            throw IllegalStateException(\"unreadable\")\n",
         ":data:desktopTest", {"aRuleThisVersionCannotReadSilencesOnlyItsOwnReminder"}),
        ("a recurrence column can stand alone", TRIGGERS, "            AND (NEW.window_start IS NOT NULL) = (NEW.recurrence_kind IS 'RANDOM_WINDOW')\n", "",
         ":data:desktopTest", {"noColumnOfARecurrenceKindStandsAlone"}),
        ("a missing month day falls back to the weekday", RRULE,
         "byMonthDay.isNotEmpty() && plainDays.isNotEmpty() -> fromMonthDay.filter { it.dayOfWeek in plainDays }\n        byMonthDay.isNotEmpty() -> fromMonthDay",
         "fromMonthDay.isNotEmpty() && plainDays.isNotEmpty() -> fromMonthDay.filter { it.dayOfWeek in plainDays }\n        fromMonthDay.isNotEmpty() -> fromMonthDay",
         ":core:desktopTest", {"aMonthDayAndAWeekdayMeanBoth"}),
        ("WEEKLY takes BYMONTHDAY and ignores it", RRULE, "            if (frequency == Frequency.WEEKLY && byMonthDay.isNotEmpty()) return null\n", "",
         ":core:desktopTest", {"aRuleThatCouldNeverOccurOrOverflowsIsRefused"}),
        ("a huge interval is taken", RRULE, "n in 1..MAX_INTERVAL", "n >= 1",
         ":core:desktopTest", {"aRuleThatCouldNeverOccurOrOverflowsIsRefused"}),
    ],
    "11": [
        ("edits apply in arrival order", EDITS, "val ordered = edits.sortedBy { it.created }", "val ordered = edits",
         ":core:desktopTest", {"sharedConcurrentMovesOnce_twoMovesOfOneOccurrenceLeaveItOnce"}),
        ("a correction counts as a clash", EDITS, "b.id !in a.seen && a.id !in b.seen &&", "",
         ":core:desktopTest", {"aCorrectionMadeAfterSeeingTheOtherEditIsNoClash"}),
        ("any shared field is a clash", EDITS, "shared.any { a.changes.schedule[it] != b.changes.schedule[it] } &&", "true &&",
         ":core:desktopTest", {"ownerOccurrenceClashAsks_twoRetimesAskAndARetimeAgainstARenameDoesNot"}),
        ("an added occurrence replaces the series one", EDITS, "shown[edit.id] = if (c.skip)", "shown[at] = if (c.skip)",
         ":core:desktopTest", {"anAddedOccurrenceAtASeriesTimeKeepsBoth"}),
        ("an occurrence moved in from outside is lost", EDITS, "(series(from, to) + named)", "series(from, to)",
         ":core:desktopTest", {"anOccurrenceMovedInFromOutsideTheWindowShows"}),
        ("a later-created earlier rule leaves the older running", EDITS, "segments.drop(i + 1).mapNotNull { it.first }.minOrNull()",
         "segments.drop(i + 1).mapNotNull { it.first }.filter { start == null || it > start }.minOrNull()",
         ":core:desktopTest", {"aLaterCreatedRuleWithAnEarlierDateEndsTheEarlierCreatedOne"}),
        ("edits carry no seen ids", OCCREPO, '"seen" to seen.joinToString(",")', '"seen" to ""',
         ":data:desktopTest", {"aRetimeMadeAfterSeeingTheOtherIsACorrectionNotAClash"}),
        ("reminders ignore occurrence edits", REMREPO, 'occurrencesWithEdits(s.itemId, dtstart, "", null, edits, from, to, habit.lastDone)', 'occurrencesWithEdits(s.itemId, dtstart, "", null, emptyList(), from, to, habit.lastDone)',
         ":data:desktopTest", {"aSkippedOccurrenceDoesNotFireAndAMovedOneFiresAtItsNewTime"}),
        ("an undone edit still applies", ITEMDAO, '"SELECT * FROM occurrence_edit WHERE item_id = :itemId AND deleted_at IS NULL"', '"SELECT * FROM occurrence_edit WHERE item_id = :itemId"',
         ":data:desktopTest", {"undoingASkipBringsTheOccurrenceBackEverywhere"}),
        ("edit rules dropped", TRIGGERS, "        OCCURRENCE_EDIT to editRules,\n", "",
         ":data:desktopTest", {"anEditMustNameWhatItsScopeCovers"}),
        ("keep both keeps one", OCCREPO, "                write(question.itemId, \"both-${earlier.id}\", EditScope.EXTRA,", "                if (false) write(question.itemId, \"both-${earlier.id}\", EditScope.EXTRA,",
         ":data:desktopTest", {"keepingBothKeepsTwoOccurrences"}),
        ("an edit reaches occurrences by their original date", EDITS, "if (o != null && edit.reaches(o.at)) shown[key] = change(o, c)",
         "if (o != null && key is LocalDateTime && edit.reaches(key)) shown[key] = change(o, c)",
         ":core:desktopTest", {"fromNowOnReachesOccurrencesWhereTheyAreNow"}),
        ("a confirmed week keeps the series' days", EDITS, "shown.entries.filter { (_, o) -> o != null && confirm.reaches(o.at) }.forEach { shown.remove(it.key) }", "Unit",
         ":core:desktopTest", {"aConfirmedWeekReplacesTheSeriesDaysAndKeepsWhatWasMovedOrAddedThere"}),
        ("a settled clash is asked again", EDITS, " &&\n                    here.none { c -> a.id in c.seen && b.id in c.seen }", "",
         ":core:desktopTest", {"aLaterEditThatHasSeenBothSettlesTheClash"}),
        ("a FROM week pattern is ignored", EDITS, "val weekly = e.changes.weekDays?.takeIf { e.scope == EditScope.FROM }", "val weekly = e.changes.weekDays?.takeIf { false }",
         ":core:desktopTest", {"aNewWeeklyPatternFromADate"}),
        ("an answer undoes instead of correcting", OCCREPO, "        val schedule = kept.changes\n", "        val schedule = EditChanges()\n",
         ":data:desktopTest", {"keepingOneEditsTimeStillMergesTheOthersTitle", "twoDevicesAnsweringDifferentlyAreAskedAgain"}),
        ("keeping both twice makes two", OCCREPO, '"both-${earlier.id}"', "newId()",
         ":data:desktopTest", {"twoDevicesKeepingBothMakeOneAddedOccurrence"}),
        ("an edit can be rewritten", TRIGGERS, "OR NEW.days IS NOT OLD.days OR NEW.changes IS NOT OLD.changes", "OR NEW.days IS NOT OLD.days",
         ":data:desktopTest", {"anEditIsWrittenOnceAndUndoneOnce"}),
        ("completions are kept by day", REMREPO, "map { LocalDateTime.parse(it.occurrence) }.toSet()", "map { LocalDateTime.parse(it.occurrence).date }.toSet().let { days -> days.map { LocalDateTime(it, MIDNIGHT) }.toSet() }",
         ":data:desktopTest", {"twoOccurrencesOnOneDayAreResolvedApart"}),
        ("an added midnight occurrence counts as timed", EDITS, "if (it == null) at.time != MIDNIGHT else", "if (it == null) true else",
         ":data:desktopTest", {"anAddedOccurrenceOnAWholeDayItemFiresAtTheAnchor"}),
    ],
    "06": [
        ("a no counts as presence", PRESENCE, "yes == true || rating != null", "yes != null || rating != null",
         ":core:desktopTest", {"aYesAnyRatingAndANumberAboveZeroCountAndANoDoesNot"}),
        ("a zero counts as presence", PRESENCE, "(number ?: 0.0) > 0.0", "number != null",
         ":core:desktopTest", {"aYesAnyRatingAndANumberAboveZeroCountAndANoDoesNot"}),
        ("the day always starts at midnight", PRESENCE, "if (at.time < dayStart) at.date.plus(-1, DateTimeUnit.DAY) else at.date", "at.date",
         ":core:desktopTest", {"aLogAfterMidnightCountsForYesterdayWhenTheDayStartsLater"}),
        ("a rolling habit ignores its last Log", RECUR, "lastDone?.plus(every, unit) ?: dtstart.date", "dtstart.date",
         ":core:desktopTest", {"aRollingHabitIsDueAPeriodAfterItsLastLog"}),
        ("an overdue rolling habit waits a period", RECUR, "var day = maxOf(due, from.date)", "var day = if (due < from.date) from.date.plus(every, unit) else due",
         ":core:desktopTest", {"anOverdueRollingHabitIsDueToday"}),
        ("a paused habit still shows", OCCREPO, "            .filter { !habit.paused(it, recurrence.timed(it, edits, item.startTime != null)) }\n", "\n",
         ":data:desktopTest", {"tendrilPauseWindow_noOccurrencesWhilePausedAndOnlyHabitsPause"}),
        ("a paused habit still fires", REMREPO, "!in resolved && !habit.paused(it, timed(it)) }", "!in resolved }",
         ":data:desktopTest", {"aPausedHabitsReminderIsQuietUntilThePauseEnds"}),
        ("a Logged occurrence still fires", REMREPO, "habit.unlogged(recurrence.occurrencesWithEdits(", "(recurrence.occurrencesWithEdits(",
         ":data:desktopTest", {"sharedOneReminderPath_aHabitsReminderIsAReminderRowAndQuietOnceLogged"}),
        ("a Log naming nothing quiets the whole day", HABITS, "            if (n > 0) left[day] = n - 1\n            n == 0", "            n == 0 && day !in left",
         ":data:desktopTest", {"aLogNamingNoOccurrenceQuietsOnlyOneOfTheDays"}),
        ("a deleted tracker keeps its habits", TRACKERS, "mapOf(TRACKER to listOf(trackerId), ITEM to habits,", "mapOf(TRACKER to listOf(trackerId), ITEM to emptyList(),",
         ":data:desktopTest", {"deletingATrackerDeletesItsHabitsAndDeletingAHabitKeepsTheTracker"}),
        ("a habit on a tracker deleted elsewhere still fires", REMDAO, "AND t.deleted_at IS NULL ", "",
         ":data:desktopTest", {"aHabitMadeOnATrackerDeletedElsewhereCountsAsDeleted"}),
        ("a purge leaves goals behind", TRACKERS, "        targets.getValue(GOAL).forEach { writes.merger.purge(store, it) }\n", "",
         ":data:desktopTest", {"aTrackersGoalsGoWithIt"}),
        ("a Log of the wrong kind is taken", TRACKERS, "        require(fits) { \"a $type tracker Logs a ${type.lowercase()}\" }\n", "",
         ":data:desktopTest", {"aSecondDailyGoalAChoiceHabitAndAValueOfTheWrongKindAreRefused"}),
        ("undo takes the latest time", TRACKERS, ".maxByOrNull { Stamp(it.hlc, it.device) }", ".maxByOrNull { it.at }",
         ":data:desktopTest", {"undoTakesTheLogMadeLastNotTheLatestTime"}),
        ("tracker rules dropped", TRIGGERS, "        TRACKER to trackerRules,\n", "",
         ":data:desktopTest", {"trackerAndReadingRulesHold"}),
        ("reading rules dropped", TRIGGERS, "        TRACKER_READING to readingRules,\n", "",
         ":data:desktopTest", {"trackerAndReadingRulesHold"}),
        ("a habit needs no tracker", TRIGGERS, "            AND (NEW.tracker_id IS NOT NULL) = (NEW.kind = 'HABIT')\n", "",
         ":data:desktopTest", {"trackerAndReadingRulesHold"}),
        ("any item pauses", TRIGGERS, "            AND (NEW.kind = 'HABIT' OR (NEW.pause_from IS NULL AND NEW.pause_until IS NULL AND NEW.block_id IS NULL AND NEW.duration_min IS NULL))\n", "",
         ":data:desktopTest", {"tendrilPauseWindow_noOccurrencesWhilePausedAndOnlyHabitsPause", "tendrilPlannerFields_aHabitKeepsItsBlockAndLengthAndATaskMayNot"}),
        ("a task may lose its status", TRIGGERS, "            AND (NEW.status IS NULL) = (NEW.kind IN ('EVENT', 'HABIT', 'ACTIVITY'))\n", "",
         ":data:desktopTest", {"aTaskWithoutAStatusIsRefused"}),
    ],
    "06b": [
        ("a block's end is part of it", PLANNER, "t >= it.start && t < it.end", "t >= it.start && t <= it.end",
         ":core:desktopTest", {"aSetTimeAtABlocksStartBelongsToThatBlockAndAtItsEndToTheNext"}),
        ("weekday times ignored", PLANNER, "blocks.map { it.on(d.dayOfWeek) }", "blocks",
         ":core:desktopTest", {"aWeekdayTimeMovesTheBlockOnThatDayOnlyAndALaterOneWins"}),
        ("the first weekday time wins", PLANNER, "overrides.lastOrNull { day in it.days }", "overrides.firstOrNull { day in it.days }",
         ":core:desktopTest", {"aWeekdayTimeMovesTheBlockOnThatDayOnlyAndALaterOneWins"}),
        ("suggestions ignore the week's load", PLANNER, "    habits.forEach { addLoad(it, weekly = false) }\n", "",
         ":core:desktopTest", {"aSuggestionKeepsTheBusiestDayLightest", "onATieForTheBusiestDayTheEvenerWeekWins"}),
        ("no tiebreak by even load", PLANNER, ", { p ->\n                days.sumOf", ", { p -> 0L + 0 * \n                days.sumOf",
         ":core:desktopTest", {"onATieForTheBusiestDayTheEvenerWeekWins"}),
        ("a confirmed week is still suggested", PLANNER, "if (h.confirmed || n == 0)", "if (n == 0)",
         ":core:desktopTest", {"confirmedDaysArePlacedAsConfirmedWhateverTheSuggestionWas"}),
        ("a suggestion leaves no load", PLANNER, "        pick.forEach { load[it] = load.getValue(it) + h.durationMin }\n", "",
         ":core:desktopTest", {"aLaterNAWeekHabitIsSuggestedOnTheLoadTheEarlierOnesLeft"}),
        ("n a day ignores its slots", PLANNER, "return o.original?.let { slots?.getOrNull(it.time.second) } ?: habitBlock", "return habitBlock",
         ":core:desktopTest", {"nADaySpreadsEvenlyOverTheBlocksInTheirOrderOrSitsInTheBlocksItNames"}),
        ("an edit's no-block falls back", PLANNER, "o.block?.let { return it.value }", "o.block?.value?.let { return it }",
         ":core:desktopTest", {"anEditsBlockWinsAndNoBlockMeansAnyTime"}),
        ("an edit's time is ignored", PLANNER, "if (h.setTime || rule?.setsTimes == true || o.ownTime)", "if (h.setTime || rule?.setsTimes == true)",
         ":core:desktopTest", {"anOccurrenceAnEditGaveATimeIsPlacedByThatTime"}),
        ("the day's rule sets no time", PLANNER, "if (h.setTime || rule?.setsTimes == true || o.ownTime)", "if (h.setTime || o.ownTime)",
         ":core:desktopTest", {"aRuleSetFromADateIsTheOnePlacedFromThen"}),
        ("the rule in force is the item's own", EDITS, "Recurrence? = patternsOf(edits.sortedBy { it.created }).ruleOn(day) ?: this", "Recurrence? = this",
         ":core:desktopTest", {"aRuleSetFromADateIsTheOnePlacedFromThen"}),
        ("a confirmed day before the start", EDITS, "if (confirmed >= dtstart && ", "if (",
         ":core:desktopTest", {"aConfirmedDayOutsideTheHabitsDaysOrBeforeItsStartIsNotPlaced"}),
        ("a confirmed day off the habit's days", EDITS, "(rule !is Recurrence.Planned || day in rule.days)", "true",
         ":core:desktopTest", {"aConfirmedDayOutsideTheHabitsDaysOrBeforeItsStartIsNotPlaced"}),
        ("n a day on every day", RECUR, "if (day.dayOfWeek in days) {\n                    for (i in 0 until n)", "if (true) {\n                    for (i in 0 until n)",
         ":core:desktopTest", {"aPlannedDaysOccurrencesHaveNoTimeOfTheirOwnAndOnlyItsDays"}),
        ("no blocks on a new database", TRIGGERS, "    override fun onCreate(connection: SQLiteConnection) = seedBlocks(connection)\n\n", "",
         ":data:desktopTest", {"aNewDatabaseHasTendrilsFiveBlocks", "twoDevicesSeedTheSameBlocksAndAnEditOnOneReachesTheOther"}),
        ("no blocks on an upgrade", DATABASE, "onPostMigrate(connection: SQLiteConnection) = seedBlocks(connection)", "onPostMigrate(connection: SQLiteConnection) = Unit",
         ":data:desktopTest", {"aDatabaseUpgradedToTimeBlocksGetsTheDefaults"}),
        ("named blocks need not match n", TRIGGERS, "+ 1 = NEW.plan_n", "+ 1 > 0",
         ":data:desktopTest", {"plannedAndBlockRulesHold"}),
        ("empty block ids", TRIGGERS, "\n                        AND instr(',' || NEW.plan_blocks || ',', ',,') = 0", "",
         ":data:desktopTest", {"plannedAndBlockRulesHold"}),
        ("n a day with a set time", TRIGGERS, " AND NEW.start_time IS NULL\n", "\n",
         ":data:desktopTest", {"plannedAndBlockRulesHold"}),
        ("a task may be planned", TRIGGERS, "NOT IN ('ROLLING', 'PLANNED')", "NOT IN ('ROLLING')",
         ":data:desktopTest", {"plannedAndBlockRulesHold"}),
        ("block rules dropped", TRIGGERS, "        HABIT_BLOCK to blockRules,\n", "",
         ":data:desktopTest", {"plannedAndBlockRulesHold"}),
        ("a paused habit is planned", HABITS, "\n                    .filter { o -> !state.paused(o, recurrence.timed(o, mine, h.startTime != null)) },", ",",
         ":data:desktopTest", {"aPausedHabitAndOneWhoseTrackerIsDeletedAreNotPlanned"}),
        ("a paused day is suggested", HABITS, " && !state.pausedOn(d) &&", " &&",
         ":data:desktopTest", {"aSuggestionAvoidsTheDaysOtherHabitsFillAndThePausedOnes"}),
        ("a skipped day is suggested", HABITS, "mine.none { it.changes.skip && it.reaches(LocalDateTime(d, start.time)) }", "true",
         ":data:desktopTest", {"aSuggestionAvoidsTheDaysOtherHabitsFillAndThePausedOnes"}),
        ("a whole-day occurrence counts for the day before", HABITS, "if (timed) dayOf(o.at, dayStart) else o.at.date", "dayOf(o.at, dayStart)",
         ":data:desktopTest", {"aWholeDayOccurrenceIsPausedOnItsOwnDateWhenTheDayStartsLater"}),
        ("any week's confirmation counts", HABITS, "it.scope == EditScope.WEEK && it.date == monday && ", "it.scope == EditScope.WEEK && ",
         ":data:desktopTest", {"anNAWeekHabitIsSuggestedUntilThisWeekIsConfirmedThenPlaced"}),
        ("habits on one tracker share a pause", HABITS, "pauseFrom = h.pauseFrom?.let(LocalDate::parse)", "pauseFrom = habits.last { it.trackerId == h.trackerId }.pauseFrom?.let(LocalDate::parse)",
         ":data:desktopTest", {"twoHabitsOnOneTrackerPauseOnTheirOwn"}),
        ("an edit's block is not written", EDITCODEC, '        c.block?.let { fields["block"] = JsonPrimitive(it.value) }\n', "",
         ":data:desktopTest", {"anOccurrencesBlockTravelsInItsEditAndNoneMeansAnyTime"}),
        ("no block reads as unchanged", EDITCODEC, 'o["block"]?.jsonPrimitive?.let { Patch(it.contentOrNull) }', 'o["block"]?.jsonPrimitive?.contentOrNull?.let { Patch(it) }',
         ":data:desktopTest", {"anOccurrencesBlockTravelsInItsEditAndNoneMeansAnyTime"}),
        ("n a day reminds at the anchor", REMREPO, "blockStart(o) ?: anchor", "anchor",
         ":data:desktopTest", {"anNADayHabitRemindsAtTheStartOfEachOfItsBlocks", "aLoggedOccurrenceIsQuietAndABlocksOwnDayAndOrderAreFollowed"}),
        ("reminders ignore a block's weekday times", REMREPO, "?.on(o.at.dayOfWeek)?.let", "?.let",
         ":data:desktopTest", {"aLoggedOccurrenceIsQuietAndABlocksOwnDayAndOrderAreFollowed"}),
        ("firings taken in occurrence order", REMREPO, ".filter { (after == null || it > after) && it != skip }\n                    .minOrNull()",
         ".firstOrNull { (after == null || it > after) && it != skip }",
         ":data:desktopTest", {"aLoggedOccurrenceIsQuietAndABlocksOwnDayAndOrderAreFollowed"}),
        ("the search starts at the last firing", REMREPO, "LocalDateTime(it.date.plus(-back, DateTimeUnit.DAY), MIDNIGHT)",
         "LocalDateTime(it.date.plus(-(s.offsetMin.floorDiv(MINUTES_PER_DAY) + 1), DateTimeUnit.DAY), it.time)",
         ":data:desktopTest", {"aWholeDayItemRemindedBeforeItsAnchorStillFiresLaterThatDay", "anNADayHabitRemindsAtTheStartOfEachOfItsBlocks"}),
    ],
    "07": [
        ("overlaps counted twice", TOTALS, "val from = reached?.let { maxOf(it, start) } ?: start", "val from = start",
         ":core:desktopTest", {"overlappingSpansCountOnceAndApartOnesAddUp"}),
        ("a span counts for the day it ends", TOTALS, "spans.groupBy { dayOf(it.start, dayStart) }", "spans.groupBy { dayOf(it.end ?: now, dayStart) }",
         ":core:desktopTest", {"aSpanCountsWhollyForTheDayItStarted"}),
        ("the goal week starts on Sunday", TOTALS, "today.plus(1 - today.dayOfWeek.isoDayNumber, DateTimeUnit.DAY)", "today.plus(-today.dayOfWeek.isoDayNumber, DateTimeUnit.DAY)",
         ":core:desktopTest", {"goalWindowsAreTheDayTheWeekFromMondayTheMonthFromThe1stAndAMilestones400Days"}),
        ("a kept timer is asked again at once", TOTALS, "secondsBetween(maxOf(span.start, keptAt ?: span.start), now)", "secondsBetween(span.start, now)",
         ":core:desktopTest", {"aTimerIsAskedAboutPastTwelveHoursAndAgainTwelveHoursAfterItWasKept"}),
        ("habits in a block by id only", PLANNER, "compareBy<Placed>({ it.sortOrder }, { it.itemId },", "compareBy<Placed>({ it.itemId },",
         ":core:desktopTest", {"habitsInABlockFollowTheirManualOrderThenTheirId"}),
        ("finishing a task leaves its timer", REPO, "TIME_SPAN to if (status == TaskStatus.PENDING) emptyList() else times.runningOf(listOf(id))", "TIME_SPAN to emptyList<String>()",
         ":data:desktopTest", {"finishingOrDeletingATaskOrHabitStopsItsTimerAndALogDoesNot"}),
        ("deleting a task leaves its timer", REPO, "mapOf(ITEM to ids, TIME_SPAN to times.runningOf(ids))", "mapOf(ITEM to ids, TIME_SPAN to emptyList())",
         ":data:desktopTest", {"finishingOrDeletingATaskOrHabitStopsItsTimerAndALogDoesNot"}),
        ("resolving any occurrence stops today's timer", REPO, ", occurrence = occurrence.date)", ")",
         ":data:desktopTest", {"resolvingAPastOccurrenceLeavesTodaysTimerRunning"}),
        ("deleting a tracker leaves its habits' timers", TRACKERS, "TIME_SPAN to times.runningOf(habits))", "TIME_SPAN to emptyList())",
         ":data:desktopTest", {"finishingOrDeletingATaskOrHabitStopsItsTimerAndALogDoesNot"}),
        ("no sweep after an import", FOLDER, ".also { afterImport() }", "",
         ":data:desktopTest", {"aTaskFinishedOnAnotherDeviceStopsTheTimerHereWhenItArrives"}),
        ("keep rewrites the span's end", TIMEREPO, 'store.put(row.edit(KEPT, clock.tick(), mapOf("kept_at" to seconds(at))))',
         'store.put(row.edit(KEPT, clock.tick(), mapOf("kept_at" to seconds(at))).edit(END, clock.tick(), mapOf("ended_at" to null)))',
         ":data:desktopTest", {"aStaleKeepOrStartEditDoesNotReopenOrReviveASpan"}),
        ("an edit rewrites the end", TIMEREPO, 'set(END, "ended_at", end?.let(::seconds))', 'edited = edited.edit(END, s, mapOf("ended_at" to end?.let(::seconds)))',
         ":data:desktopTest", {"aCommentWrittenOnOneDeviceDoesNotReopenATimerStoppedOnAnother"}),
        ("an edit rewrites deletion", TIMEREPO, 'set(START, "started_at", seconds(start))', 'set(START, "started_at", seconds(start)); edited = edited.edit(GONE, s, mapOf("deleted_at" to null))',
         ":data:desktopTest", {"aStaleKeepOrStartEditDoesNotReopenOrReviveASpan"}),
        ("a deleted span is edited", TIMEREPO, '            require(row.value(GONE, "deleted_at") == null) { "span $spanId is deleted" }\n', "",
         ":data:desktopTest", {"aDeletedSpanOrOneOnADeletedOwnerIsNotEditedAndDeletingTwiceChangesNothing"}),
        ("a stopped span is kept", TIMEREPO, 'require(row.value(END, "ended_at") == null && row.value(GONE, "deleted_at") == null) { "span $spanId is not running" }', "Unit",
         ":data:desktopTest", {"endingAtTheLimitCountsFromTheLastKeep"}),
        ("the limit ignores a keep", TIMEREPO, "maxOf(span.start, span.keptAt ?: span.start).toInstant", "span.start.toInstant",
         ":data:desktopTest", {"endingAtTheLimitCountsFromTheLastKeep"}),
        ("deleting twice restamps", TIMEREPO, 'if (row.value(GONE, "deleted_at") == null) {', "if (true) {",
         ":data:desktopTest", {"aDeletedSpanOrOneOnADeletedOwnerIsNotEditedAndDeletingTwiceChangesNothing"}),
        ("totals ignore a later day start", TIMEREPO, "LocalDateTime(days.max().plus(1, DateTimeUnit.DAY), dayStart)", "LocalDateTime(days.max().plus(1, DateTimeUnit.DAY), MIDNIGHT)",
         ":data:desktopTest", {"aPersonalDayStartingLaterCountsAnEarlySpanForTheDayBefore"}),
        ("a deleted owner's time counts", TIMESPAN, "\"WHERE s.deleted_at IS NULL AND i.deleted_at IS NULL AND t.deleted_at IS NULL AND i.kind IN ('TASK', 'HABIT', 'ACTIVITY') \" +\n            \"AND s.started_at",
         "\"WHERE s.deleted_at IS NULL AND t.deleted_at IS NULL AND i.kind IN ('TASK', 'HABIT', 'ACTIVITY') \" +\n            \"AND s.started_at",
         ":data:desktopTest", {"aDeletedOwnerOrADeletedTrackersHabitDropsOutOfTotals"}),
        ("a deleted tracker's habit counts", TIMESPAN, "\"WHERE s.deleted_at IS NULL AND i.deleted_at IS NULL AND t.deleted_at IS NULL AND i.kind IN ('TASK', 'HABIT', 'ACTIVITY') \" +\n            \"AND s.started_at",
         "\"WHERE s.deleted_at IS NULL AND i.deleted_at IS NULL AND i.kind IN ('TASK', 'HABIT', 'ACTIVITY') \" +\n            \"AND s.started_at",
         ":data:desktopTest", {"aHabitMadeOnATrackerDeletedElsewhereDropsOutOfTotals"}),
        ("an activity may be purged", REPO, '        require(dao.items(listOf(id)).singleOrNull()?.kind != ItemKind.ACTIVITY.name) { "an activity is deleted, never deleted forever" }\n', "",
         ":data:desktopTest", {"chronicleActivityDeleteRefused_anActivityIsNeverDeletedForGoodButIsDeletedWithItsTime"}),
        ("an activity row may be deleted", TRIGGERS, "BEFORE DELETE ON item WHEN OLD.kind = 'ACTIVITY' ", "BEFORE DELETE ON item WHEN 0 ",
         ":data:desktopTest", {"chronicleActivityDeleteRefused_anActivityIsNeverDeletedForGoodButIsDeletedWithItsTime"}),
        ("deleting an activity leaves its time", ACTIVITIES, '        for (span in targets.getValue(TIME_SPAN)) store.put(requireNotNull(store.row(span)).edit(GONE, s, mapOf("deleted_at" to s.hlc)))\n', "",
         ":data:desktopTest", {"chronicleActivityDeleteRefused_anActivityIsNeverDeletedForGoodButIsDeletedWithItsTime"}),
        ("a span on any kind", TRIGGERS, """private val spanRules = "COALESCE((SELECT kind FROM item WHERE id = NEW.item_id) IN ('TASK', 'HABIT', 'ACTIVITY'), 1)\"""", """private val spanRules = "1\"""",
         ":data:desktopTest", {"tendrilExactlyOneOwner_aSpanHasOneOwnerOfAKindThatIsTimed"}),
        ("a span moves owner", TRIGGERS, "BEFORE UPDATE ON time_span WHEN NEW.item_id IS NOT OLD.item_id ", "BEFORE UPDATE ON time_span WHEN 0 ",
         ":data:desktopTest", {"tendrilExactlyOneOwner_aSpanHasOneOwnerOfAKindThatIsTimed"}),
        ("icons on any item", TRIGGERS, "            AND (NEW.kind = 'ACTIVITY' OR (NEW.icon IS NULL AND NEW.color IS NULL))\n", "",
         ":data:desktopTest", {"activitiesArchiveAndKeepTheirOrderAndTheirColumnsStayTheirs"}),
        ("archived on any item", TRIGGERS, "            AND (NEW.archived IS NOT NULL) = (NEW.kind = 'ACTIVITY')\n", "",
         ":data:desktopTest", {"activitiesArchiveAndKeepTheirOrderAndTheirColumnsStayTheirs"}),
        ("a task has a manual order", TRIGGERS, "            AND (NEW.sort_order IS NULL OR NEW.kind IN ('ACTIVITY', 'HABIT'))\n", "",
         ":data:desktopTest", {"activitiesArchiveAndKeepTheirOrderAndTheirColumnsStayTheirs"}),
        ("an activity has dates", TRIGGERS, "\n            AND (NEW.kind <> 'ACTIVITY' OR (NEW.start_date IS NULL AND NEW.start_time IS NULL AND NEW.due_date IS NULL AND NEW.recurrence_kind IS NULL))", "",
         ":data:desktopTest", {"activitiesArchiveAndKeepTheirOrderAndTheirColumnsStayTheirs"}),
    ],
    "08": [
        ("names compare with case", LABELKEY, "fun nameKey(name: String): String = name.trim().lowercase()", "fun nameKey(name: String): String = name.trim()",
         ":core:desktopTest", {"namesCompareIgnoringCaseAndOuterSpaces"}),
        ("names compare in any Unicode form", LABELS, "internal fun labelKey(name: String): String = nameKey(nfc(name))", "internal fun labelKey(name: String): String = nameKey(name)",
         ":data:desktopTest", {"aNameStoredInAnotherUnicodeFormStillCountsAsTheSameName"}),
        ("a new label's colour is not its name's", LABELS, "(color ?: colorForName(clean))", "(color ?: 0L)",
         ":data:desktopTest", {"namesAreUniqueIgnoringCaseAndANewLabelTakesItsColourFromItsName"}),
        ("names need not be unique", LABELS, 'require(dao.liveLabels().none { it.id != except && labelKey(it.name) == labelKey(clean) }) { "there is already a label \\"$clean\\"" }', "Unit",
         ":data:desktopTest", {"namesAreUniqueIgnoringCaseAndANewLabelTakesItsColourFromItsName"}),
        ("a dead label is edited", LABELS, "        live(id)\n        check()\n", "        check()\n",
         ":data:desktopTest", {"deletingASurvivorClearsWhatCarriedTheLabelsMergedIntoItAndADeadLabelIsNotEdited"}),
        ("the merge keeps the one made last", LABELS, "val first = same.minOf { it.id }", "val first = same.maxOf { it.id }",
         ":data:desktopTest", {"twoLabelsOfOneNameMadeApartMergeIntoTheOneMadeFirstWithWhatCarriedThem", "aRenameOntoAnotherDevicesNameMergesTheSameWay"}),
        ("labels never merge", LABELS, "if (into.isEmpty()) return@write", "return@write",
         ":data:desktopTest", {"twoLabelsOfOneNameMadeApartMergeIntoTheOneMadeFirstWithWhatCarriedThem", "aRenameOntoAnotherDevicesNameMergesTheSameWay"}),
        ("a merged label reads as none", LABELS, "{ it.mergedInto?.let(byId::get) }", "{ null }",
         ":data:desktopTest", {"aMergeChainReadsToItsEndAndAChainEndingInADeletedLabelReadsAsNone", "somethingLabelledOnAPeerThatHadNotSeenTheMergeReadsAsTheSurvivor"}),
        ("deleting leaves what carried merged labels", LABELS, "val same = dao.allLabels().let { all -> val r = resolver(all); all.map { it.id }.filter { r(it) == id } }", "val same = listOf(id)",
         ":data:desktopTest", {"deletingASurvivorClearsWhatCarriedTheLabelsMergedIntoItAndADeadLabelIsNotEdited"}),
        ("deleting leaves what carried it", LABELS, '            store.put(requireNotNull(store.row(member)).edit(LABELLED, s, mapOf("label_id" to null)))\n', "",
         ":data:desktopTest", {"deletingASurvivorClearsWhatCarriedTheLabelsMergedIntoItAndADeadLabelIsNotEdited"}),
        ("a label outside its scope is set", LABELS, '        require(applies == LabelScope.ALL || applies == scope) { "label ${label.name} is not offered here" }\n', "",
         ":data:desktopTest", {"chronicleAppliesToScope_aLabelIsOfferedOnlyWhereItAppliesAndNarrowingHides"}),
        ("a habit is offered activity labels", LABELS, "if (kind == ItemKind.ACTIVITY) LabelScope.ACTIVITY else LabelScope.ALL", "LabelScope.ACTIVITY",
         ":data:desktopTest", {"chronicleAppliesToScope_aLabelIsOfferedOnlyWhereItAppliesAndNarrowingHides"}),
        ("a task is labelled", LABELS, '        require(kind == ItemKind.ACTIVITY || kind == ItemKind.HABIT) { "a ${item.kind} carries no label" }\n', "",
         ":data:desktopTest", {"chronicleOneCategoryPerRow_aSecondLabelReplacesTheFirstAndAnyKindElseCarriesNone"}),
        ("any item carries a label", TRIGGERS, "            AND (NEW.label_id IS NULL OR NEW.kind IN ('ACTIVITY', 'HABIT'))\n", "",
         ":data:desktopTest", {"chronicleOneCategoryPerRow_aSecondLabelReplacesTheFirstAndAnyKindElseCarriesNone"}),
        ("label rules dropped", TRIGGERS, "        LABEL to labelRules,\n", "",
         ":data:desktopTest", {"chronicleAppliesToScope_aLabelIsOfferedOnlyWhereItAppliesAndNarrowingHides"}),
        ("a label's total is everything's", TIMEREPO, "dao.counted(from, to, itemId, labelIds != null, labelIds.orEmpty())", "dao.counted(from, to, itemId, false, labelIds.orEmpty())",
         ":data:desktopTest", {"chronicleActivityAndCategoryTotals_40MinutesOfReadingTotal40ForLeisure"}),
        ("a label's total leaves out labels merged into it", TIMEREPO, "all.map { it.id }.filter { r(it) == id }", "listOf(id)",
         ":data:desktopTest", {"deletingASurvivorClearsWhatCarriedTheLabelsMergedIntoItAndADeadLabelIsNotEdited"}),
        ("an activity shows a merged label as stored", ACTIVITIES, "it.sortOrder, label(it.labelId))", "it.sortOrder, it.labelId)",
         ":data:desktopTest", {"somethingLabelledOnAPeerThatHadNotSeenTheMergeReadsAsTheSurvivor"}),
        ("a label reads as stored", LABELS, "suspend fun labelOf(itemId: String): String? = items.items(listOf(itemId)).singleOrNull()?.labelId.let(resolver(dao.allLabels()))",
         "suspend fun labelOf(itemId: String): String? = items.items(listOf(itemId)).singleOrNull()?.labelId",
         ":data:desktopTest", {"somethingLabelledOnAPeerThatHadNotSeenTheMergeReadsAsTheSurvivor", "aMergeWritesNothingOnWhatCarriedTheMergedLabelSoAChoiceMadeMeanwhileStands"}),
        ("triggers kept on an upgrade", OPEN, ".also(::dropTriggersBeforeUpgrade)", "",
         ":data:desktopTest", {"aVersion9DatabaseKeepsItsItemsAndTrackersWhenLabelsArrive"}),
    ],
    "09": [
        ("a restore stamps personal values anew", SETTINGS, "Group(Stamp(v.hlc, v.device), mapOf(VALUE to v.value))", "Group(clock.tick(), mapOf(VALUE to v.value))",
         ":data:desktopTest", {"anOldBackupNeverOutranksANewerPersonalValue"}),
        ("a restore writes device state", SETTINGS, "it.scope == SettingScope.DEVICE_PREF && it !== Settings.APP_LOCK", "it.scope != SettingScope.SECRET && it !== Settings.APP_LOCK",
         ":data:desktopTest", {"sharedFirstRunNotRestored_aNewPhoneAsksItsFirstRunQuestions", "mnemoFolderNotRestored_aRestoredPhoneDoesNotInheritTheFolderGrant"}),
        ("a restore turns the lock on", SETTINGS, " && it !== Settings.APP_LOCK }", " }",
         ":data:desktopTest", {"appLockIsPerDeviceAndNeverOnWithoutThisDevicesPin"}),
        ("the lock goes on without a PIN", SETTINGS, 'if (setting === Settings.APP_LOCK && value == true) require(get(Settings.APP_LOCK_PIN).isNotEmpty()) { "set this device\'s PIN before the lock" }', "Unit",
         ":data:desktopTest", {"appLockIsPerDeviceAndNeverOnWithoutThisDevicesPin"}),
        ("a backup carries device state", SETTINGS, "device = Settings.all.filter { it.scope == SettingScope.DEVICE_PREF }", "device = Settings.all.filter { it.scope != SettingScope.SECRET && it.scope != SettingScope.PERSONAL }",
         ":data:desktopTest", {"chronicleDeviceIdOwn_theDeviceIdIsNoSettingAndRidesInNoBackup"}),
        ("personal settings read from the device", SETTINGS, "SettingScope.PERSONAL -> dao.settings(listOf(settingId(setting.key))).singleOrNull()?.value", "SettingScope.PERSONAL -> dao.deviceValue(setting.key)",
         ":data:desktopTest", {"equipoisePersonalTravels_theThresholdAndContactsReachEveryDeviceAndTheRestoredPhone"}),
        ("a default is stored", SETTINGS, "if (value == setting.default) null else setting.encode(value)", "setting.encode(value)",
         ":data:desktopTest", {"aPersonalSettingChangedOnTwoDevicesKeepsTheLaterAndTheDefaultClearsIt"}),
        ("a restore pins a default", SETTINGS, "value.takeUnless { setting.decode(it) == setting.default }", "value",
         ":data:desktopTest", {"aRestoreClearsADevicePreferenceThatIsTheDefault"}),
        ("an unreadable day start is used", REGISTRY, "{ runCatching { LocalTime.parse(it) }.getOrNull() }", "{ LocalTime.parse(it) }",
         ":data:desktopTest", {"aValueThatDoesNotReadReadsAsTheDefaultAndOneOutOfRangeIsRefused"}),
        ("a zero timer limit is taken", REGISTRY, "v.toIntOrNull()?.takeIf { it >= 1 }?.hours", "v.toIntOrNull()?.takeIf { it >= 0 }?.hours",
         ":data:desktopTest", {"aValueThatDoesNotReadReadsAsTheDefaultAndOneOutOfRangeIsRefused"}),
        ("setting ids unmarked", STORES, 'internal fun settingId(key: String) = "setting:$key"', "internal fun settingId(key: String) = key",
         ":data:desktopTest", {"aPersonalSettingChangedOnTwoDevicesKeepsTheLaterAndTheDefaultClearsIt"}),
        ("the AI key syncs", REGISTRY, 'val AI_KEY = text("ai_key", SettingScope.SECRET)', 'val AI_KEY = text("ai_key", SettingScope.PERSONAL)',
         ":data:desktopTest", {"tendrilSecretNeverLeaves_theAiKeyIsInNoFolderBackupOrOtherDevice"}),
        ("the window frame syncs", REGISTRY, 'val WINDOW_FRAME = text("window_frame", SettingScope.DEVICE_STATE)', 'val WINDOW_FRAME = text("window_frame", SettingScope.PERSONAL)',
         ":data:desktopTest", {"tendrilLayoutPerDevice_aWindowFrameReachesNoOtherDevice"}),
        ("one key for two secrets", REGISTRY, 'text("llm_endpoint_key", SettingScope.SECRET)', 'text("ai_key", SettingScope.SECRET)',
         ":data:desktopTest", {"tendrilSecretNeverLeaves_theAiKeyIsInNoFolderBackupOrOtherDevice"}),
        ("totals ignore the day-start setting", TIMEREPO, "        val dayStart = personal.dayStart()\n", "        val dayStart = MIDNIGHT\n",
         ":data:desktopTest", {"theDayStartSetOnOneDeviceDecidesTheDayOnAnotherAtOnce"}),
        ("timers ignore the limit setting", TIMEREPO, "        val limit = personal.longRun()\n", "        val limit = com.factotum.core.time.LONG_RUN\n",
         ":data:desktopTest", {"theLongTimerLimitIsOneSettingForEveryDevice"}),
        ("a recovered device skips its own files", FOLDER, "(owner != device || readOwn)", "owner != device",
         ":data:desktopTest", {"aDeviceWhoseDatabaseWasRecoveredGetsItsSettingsBackFromItsOwnFiles"}),
    ],
    "10": [
        ("an archived name stays in the index", SEARCHINDEX, " AND COALESCE($.archived, 0) = 0", "",
         ":data:desktopTest", {"whatWasWrittenUnderAnArchivedActivityStaysFindableButItsNameAndAnythingDeletedDoNot"}),
        ("a deleted item stays in the index", SEARCHINDEX, '"$.deleted_at IS NULL AND COALESCE($.archived, 0) = 0', '"1 = 1 AND COALESCE($.archived, 0) = 0',
         ":data:desktopTest", {"chronicleTombstoneLeaves_aDeletedReminderIsNoLongerFound"}),
        ("no update trigger", SEARCHINDEX, '        "CREATE TRIGGER ${s.table}_search_update AFTER UPDATE OF ${s.watched.joinToString(", ")} ON ${s.table} BEGIN ${s.remove("OLD")} ${s.add()} END",\n', "",
         ":data:desktopTest", {"chronicleTombstoneLeaves_aDeletedReminderIsNoLongerFound"}),
        ("no insert trigger", SEARCHINDEX, '        "CREATE TRIGGER ${s.table}_search_insert AFTER INSERT ON ${s.table} BEGIN ${s.add()} END",\n', "",
         ":data:desktopTest", {"chronicleAnyWritePath_aLogWrittenAroundTheRepositoriesOrArrivingFromAPeerIsFound"}),
        ("no rebuild", SEARCHINDEX, '    if (wanted == held && held == connection.count("SELECT count(*) FROM search_fts")) return', "    return",
         ":data:desktopTest", {"anIndexThatMissesRowsIsRebuiltOnOpenAndAnUpgradedDatabaseIsIndexed"}),
        ("search from one letter", SEARCH, "if (terms.sumOf { it.length } < 2) return emptyList()", "if (terms.sumOf { it.length } < 1) return emptyList()",
         ":data:desktopTest", {"searchStartsAtTwoLetters"}),
        ("whole words only", SEARCH, '"$it*"', '"$it"',
         ":data:desktopTest", {"chronicleAccentsFolded_perch\u00e9IsFoundAsPercheAndCaseNeverMatters"}),
        ("an accent written apart splits a word", SEARCH, 'Regex("[\\\\p{L}\\\\p{N}][\\\\p{L}\\\\p{N}\\\\p{M}]*")', 'Regex("[\\\\p{L}\\\\p{N}]+")',
         ":data:desktopTest", {"chronicleAccentsFolded_perch\u00e9IsFoundAsPercheAndCaseNeverMatters"}),
        ("text inside comes before names", SEARCH, "return names.sortedWith(NEWEST.thenBy { it.text }.thenBy { it.id }) + inside.sortedWith(NEWEST.thenBy { it.id })",
         "return inside.sortedWith(NEWEST.thenBy { it.id }) + names.sortedWith(NEWEST.thenBy { it.text }.thenBy { it.id })",
         ":data:desktopTest", {"sharedOneSearch_itemsAndSessionsComeBackFromOneQueryNamesFirstThenNewest"}),
        ("oldest first", SEARCH, ".thenByDescending { it.at }", ".thenBy { it.at }",
         ":data:desktopTest", {"sharedOneSearch_itemsAndSessionsComeBackFromOneQueryNamesFirstThenNewest"}),
        ("a deleted tracker's Logs are found", SEARCH, "trackerRows[r.trackerId]?.takeIf { it.deletedAt == null }?.let { t ->", "trackerRows[r.trackerId]?.let { t ->",
         ":data:desktopTest", {"whatWasWrittenUnderAnArchivedActivityStaysFindableButItsNameAndAnythingDeletedDoNot"}),
        ("a deleted parent is ignored", SEARCH, " && (it.parentId == null || itemLive(it.parentId))", "",
         ":data:desktopTest", {"aSubtaskUnderADeletedParentIsNotFound"}),
        ("events are never finished", SEARCH, "ItemKind.EVENT.name -> repeat.kind == null && ", "ItemKind.EVENT.name -> false && ",
         ":data:desktopTest", {"aPastEventIsMarkedFinishedAndARepeatingOneIsNot"}),
        ("finished tasks are not marked", SEARCH, "else -> status == TaskStatus.DONE.name || status == TaskStatus.SKIPPED.name", "else -> false",
         ":data:desktopTest", {"finishedTasksAreFoundAndMarked"}),
    ],
    "05": [
        ("a step sits on its band's edge", SCALES, "return (level - 0.5) / levels", "return (level - 1.0) / levels",
         ":core:desktopTest", {"aStepSitsInTheMiddleOfItsBandAndReadsBackAsItself"}),
        ("a top value reads past the scale", SCALES, "return minOf(levels, (value * levels).toInt() + 1)", "return (value * levels).toInt() + 1",
         ":core:desktopTest", {"aStepSitsInTheMiddleOfItsBandAndReadsBackAsItself"}),
        ("a future day is offered", SCALES, "fun checkInOffered(day: LocalDate, today: LocalDate): Boolean = day <= today", "fun checkInOffered(day: LocalDate, today: LocalDate): Boolean = true",
         ":core:desktopTest", {"tendrilsWordsAndACheckInOnlyForADayThatHasHappened"}),
        ("an energy tap is unmarked", CHECKINS, "record(at, energy = axisValue(level, 5), sourceLevels = 5, day = day)", "record(at, energy = axisValue(level, 5), day = day)",
         ":data:desktopTest", {"tendrilEnergyRoundtrip_lowIsStoredOnTheSharedAxisAndReadsBackLow", "noMidline_theEnginesReadOnlyTwoAxisCheckInsAndAStepValueIsMarked"}),
        ("the widget is rescaled", CHECKINS, "private val WIDGET_ENERGY = listOf(0.15, 0.5, 0.85)", "private val WIDGET_ENERGY = listOf(1.0 / 6, 0.5, 5.0 / 6)",
         ":data:desktopTest", {"equipoiseWidgetEnergyOnly_pleasantnessAndMoodStayEmpty"}),
        ("the engines read one-axis taps", CHECKINDAO, "WHERE deleted_at IS NULL AND energy IS NOT NULL AND pleasantness IS NOT NULL AND at < :before", "WHERE deleted_at IS NULL AND energy IS NOT NULL AND at < :before",
         ":data:desktopTest", {"noMidline_theEnginesReadOnlyTwoAxisCheckInsAndAStepValueIsMarked"}),
        ("the engines read the judged check-in", CHECKINDAO, " AND at < :before ORDER BY at, id", " AND at <= :before ORDER BY at, id",
         ":data:desktopTest", {"theEnginesReadOnlyCheckInsMadeBeforeTheOneJudged"}),
        ("the engines read the day it is about", CHECKINS, "Logged(dayOf(LocalDateTime.parse(e.at), dayStart).toEpochDays().toInt()", "Logged((e.day?.let(LocalDate::parse) ?: dayOf(LocalDateTime.parse(e.at), dayStart)).toEpochDays().toInt()",
         ":data:desktopTest", {"aCheckInMayBeAboutAPastDayButNotAFutureOneAndTheEnginesReadTheMoment"}),
        ("the day it is about is ignored", CHECKINS, "id, made, day?.let(LocalDate::parse) ?: dayOf(made, dayStart),", "id, made, dayOf(made, dayStart),",
         ":data:desktopTest", {"aCheckInMayBeAboutAPastDayButNotAFutureOneAndTheEnginesReadTheMoment"}),
        ("a future day is taken", CHECKINS, '        require(day == null || day <= dayOf(at, personal.dayStart())) { "a check-in is about a day that has happened: $day" }\n', "",
         ":data:desktopTest", {"aCheckInMayBeAboutAPastDayButNotAFutureOneAndTheEnginesReadTheMoment", "aCheckInAfterMidnightCountsForTheDayBeforeWhenTheDayStartsLater"}),
        ("days end at midnight", CHECKINS, "        return dao.around(LocalDateTime(day, dayStart).toString(), LocalDateTime(next, dayStart).toString(),",
         "        return dao.around(LocalDateTime(day, kotlinx.datetime.LocalTime(0, 0)).toString(), LocalDateTime(next, kotlinx.datetime.LocalTime(0, 0)).toString(),",
         ":data:desktopTest", {"aCheckInAfterMidnightCountsForTheDayBeforeWhenTheDayStartsLater"}),
        ("an undo restamps", CHECKINS, 'if (row.groups.getValue(GONE).values["deleted_at"] == null) {', "if (true) {",
         ":data:desktopTest", {"aCheckInIsUndoneNotChangedAndItsNoteStaysOutOfSearch"}),
        ("a note shares the deletion's group", CHECKINS, 'suspend fun setNote(id: String, note: String?) = writes.edit(CHECK_IN, id, NOTE) { mapOf("note" to note?.trim()?.ifEmpty { null }) }',
         'suspend fun setNote(id: String, note: String?) = writes.edit(CHECK_IN, id, GONE) { mapOf("deleted_at" to null) }',
         ":data:desktopTest", {"aNoteWrittenOnOneDeviceNeverBringsBackACheckInUndoneOnAnother"}),
        ("check-in rules dropped", TRIGGERS, "        CHECK_IN to checkInRules,\n", "",
         ":data:desktopTest", {"aCheckInOutsideItsScalesIsRefused"}),
        ("a fractional mood is taken", TRIGGERS, "(typeof(NEW.mood) = 'integer' AND NEW.mood BETWEEN 1 AND 5)", "(NEW.mood BETWEEN 1 AND 5)",
         ":data:desktopTest", {"aCheckInOutsideItsScalesIsRefused"}),
    ],
    "12a": [
        ("a winning local text looks agreed", MERGE, "store.putBase(local.id, name, theirs.stamp)", "store.putBase(local.id, name, winner.stamp)",
         ":core:desktopTest", {"withThreeDevicesEveryReplacedTextIsLostSomewhereWhateverTheOrder"}),
        ("the replaced text is dropped", STAGED, "        if (lostOnes.isNotEmpty()) dao.addLost(lostOnes)\n", "",
         ":data:desktopTest", {"theLaterTextWinsAndTheEarlierIsKeptInHistoryWithOneNoticeDismissedEverywhere"}),
        ("a revival takes a fresh stamp", PAGES, 'store.put(requireNotNull(store.row(id)).edit(GONE, automatic(gone), mapOf("deleted_at" to null)))', 'store.put(requireNotNull(store.row(id)).edit(GONE, clock.tick(), mapOf("deleted_at" to null)))',
         ":data:desktopTest", {"aPurgeHoldsEvenWhenTheTrashArrivedFirstAndBroughtThePageBack"}),
        ("a revived page leaves its parents", PAGES, "for (q in generateSequence(p) { byId[it.parentId] }.take(pages.size)) {", "for (q in sequenceOf(p)) {",
         ":data:desktopTest", {"aLaterEditToASubPageBringsBackItsTrashedParents"}),
        ("a deleted block stays deleted", PAGES, "if ((latestByHand(b.edits()) ?: continue) > Stamp(b.goneHlc, b.goneDevice)) found", "if (false) found",
         ":data:desktopTest", {"aLaterEditBringsADeletedBlockBack"}),
        ("a trashed page stays trashed", PAGES, "if (q.deletedAt == null || gone >= newest) continue", "continue",
         ":data:desktopTest", {"aLaterEditBringsATrashedPageBackAndAnEarlierOneDoesNot", "aLaterEditToASubPageBringsBackItsTrashedParents"}),
        ("a live page under the trash is hidden", PAGES, "page.parentId?.takeIf { pages[it]?.deletedAt == null && it in pages && !onCycle(page, pages) }",
         "page.parentId?.takeIf { it in pages && !onCycle(page, pages) }",
         ":data:desktopTest", {"aLivePageUnderATrashedOneIsShownAtTheTopAndADeleteForeverLeavesIt"}),
        ("a cycle is out of reach", PAGES, "page.parentId?.takeIf { pages[it]?.deletedAt == null && it in pages && !onCycle(page, pages) }",
         "page.parentId?.takeIf { pages[it]?.deletedAt == null && it in pages }",
         ":data:desktopTest", {"twoPagesMovedUnderEachOtherApartAreBothShownAtTheTop"}),
        ("a cycle shows twice in the trash", PAGES, "cycleOf(it, pages).minOrNull() == it.id", "onCycle(it, pages)",
         ":data:desktopTest", {"twoPagesMovedUnderEachOtherApartAreBothShownAtTheTop"}),
        ("delete forever takes a live page", PAGES, 'kept.forEach { store.put(requireNotNull(store.row(it)).edit(PLACE, s, mapOf("parent_id" to null))) }', "",
         ":data:desktopTest", {"aLivePageUnderATrashedOneIsShownAtTheTopAndADeleteForeverLeavesIt"}),
        ("an icon clash raises a notice", PAGES, "if (page == null || (lost.tbl != PROPERTY_VALUE && current == text) || ", "if (page == null || ",
         ":data:desktopTest", {"aRenameKeepsTheIconAndAnIconOrFormatChangedApartRaisesNoNotice"}),
        ("a late notice undoes a dismissal", PAGES, 'DISMISSED to Group(loser.stamp, mapOf("dismissed_at" to null)),', 'DISMISSED to Group(clock.tick(), mapOf("dismissed_at" to null)),',
         ":data:desktopTest", {"aNoticeWrittenLateByTheOtherDeviceDoesNotUndoADismissal"}),
        ("a rename wipes the icon", PAGES, "row.groups.getValue(PAGE_TITLE).values + change", 'mapOf("title" to null, "icon" to null) + change',
         ":data:desktopTest", {"aRenameKeepsTheIconAndAnIconOrFormatChangedApartRaisesNoNotice"}),
        ("a block goes under itself", PAGES, 'require(generateSequence(parent) { byId[it]?.parentBlockId }.take(blocks.size + 1).none { it == id }) { "a block cannot go under itself" }', "",
         ":data:desktopTest", {"aBlockGoesOnlyUnderALiveBlockOfItsPageAndNeverUnderItself"}),
        ("a block goes under any block", PAGES, 'parent?.let { p -> require(blocks.any { it.id == p }) { "no block $p on page $pageId" } }', "",
         ":data:desktopTest", {"aBlockGoesOnlyUnderALiveBlockOfItsPageAndNeverUnderItself"}),
        ("History keeps every version", PAGES, "        dao.keepRevisions(pageId, KEPT)\n", "",
         ":data:desktopTest", {"historyKeepsAnEditAtMostEveryTenMinutesFiftyKeptAndRestores"}),
        ("History keeps every edit", PAGES, "if (last == null || wallMillis() - last.at >= EDIT_EVERY_MS)", "if (true)",
         ":data:desktopTest", {"historyKeepsAnEditAtMostEveryTenMinutesFiftyKeptAndRestores"}),
        ("a trashed page is a label's", LABELS, "return readChunked(on) { pages.pages(it) }.filter { it.deletedAt == null }.map { it.id }.sorted()", "return on.sorted()",
         ":data:desktopTest", {"aPageCarriesManyLabelsAndAMergedOrDeletedLabelReadsRight"}),
        ("pages leave search", SEARCHINDEX, """    Source(SearchKind.PAGE, "page", "$.title", "$.deleted_at IS NULL AND $.is_template IS NOT 1 AND TRIM($.title) <> ''", listOf("title", "deleted_at")),\n""", "",
         ":data:desktopTest", {"aPageIsFoundByATitleWordAndABodyWordAccentsFoldedAndNothingUnderTheTrash"}),
        ("a trashed page's blocks are found", SEARCH, "blocks[h.rowKey]?.takeIf { pageLive(it.pageId) }", "blocks[h.rowKey]",
         ":data:desktopTest", {"aPageIsFoundByATitleWordAndABodyWordAccentsFoldedAndNothingUnderTheTrash"}),
        ("a block moves page", TRIGGERS, 'listOf(BLOCK to listOf("page_id"), ', "listOf(",
         ":data:desktopTest", {"aBlockStaysOnItsPage"}),
    ],
    "12b": [
        ("an option merge takes a fresh stamp", DBS, 'edit(GONE, automatic(last), mapOf("deleted_at" to last.hlc, "merged_into" to survivor))',
         'edit(GONE, clock.tick(), mapOf("deleted_at" to last.hlc, "merged_into" to survivor))', ":data:desktopTest", {"anOptionMergeIsNoEditThatBringsATrashedDatabaseBack"}),
        ("a deleted option stays deleted", DBS, "if (at.byHand && at > Stamp(o.goneHlc, o.goneDevice)) found[o.id]", "if (false) found[o.id]",
         ":data:desktopTest", {"aDeletedOptionReadsAsEmptyKeepsThePickAndComesBackWhenPickedLaterElsewhere"}),
        ("a merged option reads as none", DBS, "generateSequence(start?.let(byId::get)) { it.mergedInto?.let(byId::get) }", "generateSequence(start?.let(byId::get)) { null }",
         ":data:desktopTest", {"twoOptionsOfOneNameMadeApartMergeIntoTheFirst"}),
        ("same-name options stay apart", DBS, ".values.filter { it.size > 1 }", ".values.filter { false }",
         ":data:desktopTest", {"twoOptionsOfOneNameMadeApartMergeIntoTheFirst", "aFilterOnAnOptionMergedSinceStillMatches"}),
        ("a type change makes no options", DBS, "made = texts.map { newId() to it }", "made = emptyList()",
         ":data:desktopTest", {"aTypeChangeRewritesNoValueAndChangingBackReadsAsBefore", "aDeletedOptionsNameIsFreeForATypeChange"}),
        ("a deleted option's name is taken", DBS, "val known = options.map { it.id }.toSet() + options.filter { it.deletedAt == null }.map { labelKey(it.name) }",
         "val known = options.flatMap { listOf(it.id, labelKey(it.name)) }.toSet()", ":data:desktopTest", {"aDeletedOptionsNameIsFreeForATypeChange"}),
        ("a Multi-select ignores its picks", DBS, "(picks.mapNotNull(resolve) + tokensOf(raw)", "(tokensOf(raw)",
         ":data:desktopTest", {"multiSelectPicksMadeApartBothStay"}),
        ("a Multi-select reads as no Select", DBS, " ?: picks.mapNotNull(resolve).minByOrNull { order.getValue(it) })", ")",
         ":data:desktopTest", {"picksReadFromAnotherTypesValueCanBeTakenOutAndAMultiSelectReadsAsASelect"}),
        ("unpick leaves the text", DBS, "val kept = tokens.filter { optionOfToken(it, options, r) != optionId }", "val kept = tokens",
         ":data:desktopTest", {"picksReadFromAnotherTypesValueCanBeTakenOutAndAMultiSelectReadsAsASelect"}),
        ("a cell clash is silent", PAGE, "setOf(PAGE_TITLE, BLOCK_TEXT, CELL, NODE_TEXT, EDGE_LABEL)", "setOf(PAGE_TITLE, BLOCK_TEXT, NODE_TEXT, EDGE_LABEL)",
         ":data:desktopTest", {"aCellSetApartKeepsTheLaterAndTheEarlierIsInHistoryWithANotice"}),
        ("a new cell gets a base", DBS, "                store.put(Row(PROPERTY_VALUE, id, mapOf(", "                writes.merger.created(store, Row(PROPERTY_VALUE, id, mapOf(",
         ":data:desktopTest", {"aCellSetApartKeepsTheLaterAndTheEarlierIsInHistoryWithANotice"}),
        ("a notice shows an option id", PAGES, "val text = cell?.let { c -> raw?.let { r -> databases.options(listOf(r)).singleOrNull()?.takeIf { it.propertyId == c.propertyId }?.name } } ?: raw.orEmpty()",
         "val text = raw.orEmpty()", ":data:desktopTest", {"aCellSetApartKeepsTheLaterAndTheEarlierIsInHistoryWithANotice"}),
        ("an empty cell is written", DBS, "                if (v == null) return@write\n", "",
         ":data:desktopTest", {"clearingACellNoOneFilledHereWritesNothingOverAValueFilledElsewhere"}),
        ("labelled pages are no rows", DBS, "        val labelled = if (doorway == null) emptyList() else {", "        val labelled = if (true) emptyList<String>() else {",
         ":data:desktopTest", {"theRowsAreThePagesMadeInItAndThePagesCarryingItsLabel"}),
        ("a filter misses a merged option", DBS, "view.filterValue?.let { optionResolver(options)(it) ?: it }", "view.filterValue",
         ":data:desktopTest", {"aFilterOnAnOptionMergedSinceStillMatches"}),
        ("numbers sort as text", DBS, "PropertyType.NUMBER -> compareValues(a.number, b.number)", "PropertyType.NUMBER -> compareValues(a.text, b.text)",
         ":data:desktopTest", {"aViewSortsByTypeWithEmptyLastAndFiltersByType"}),
        ("empty cells sort first", DBS, "return full.sortedWith(if (view.sortDescending) byValue.reversed() else byValue) + empty",
         "return empty + full.sortedWith(if (view.sortDescending) byValue.reversed() else byValue)", ":data:desktopTest", {"aViewSortsByTypeWithEmptyLastAndFiltersByType"}),
        ("the none column comes last", DBS, "val columns = listOf<String?>(null) + options(property.id).map { it.id }",
         "val columns = options(property.id).map<SelectOption, String?> { it.id } + listOf<String?>(null)", ":data:desktopTest", {"aBoardHasANoneColumnFirstThenTheOptionsInOrderAndMovingACardIsAPick"}),
        ("a cell edit leaves a trashed row", PAGES, "cells[p.id].orEmpty() + picks[p.id].orEmpty() + schema[p.id].orEmpty()", "schema[p.id].orEmpty()",
         ":data:desktopTest", {"aCellOrASchemaEditAfterATrashBringsThePageBack"}),
        ("a schema edit leaves a trashed database", PAGES, "cells[p.id].orEmpty() + picks[p.id].orEmpty() + schema[p.id].orEmpty()", "cells[p.id].orEmpty() + picks[p.id].orEmpty()",
         ":data:desktopTest", {"aCellOrASchemaEditAfterATrashBringsThePageBack"}),
        ("a revived database leaves its rows", PAGES, "                    branch(q.id, pages) { it.deletedAt == q.deletedAt }.forEach { found[it.id] = Stamp(it.goneHlc, it.goneDevice) }\n", "",
         ":data:desktopTest", {"aRevivedDatabaseBringsBackTheRowsTrashedWithIt"}),
        ("History forgets picks", PAGES, "val want = picks[property]?.contains(option) ?: live", "val want = live",
         ":data:desktopTest", {"historyGivesBackAMultiSelectsPicks"}),
        ("the last view is deleted", DBS, 'require(dao.viewsOf(view.databaseId).count { it.deletedAt == null } > 1) { "a database keeps one view" }', "",
         ":data:desktopTest", {"aDatabaseKeepsOneViewAndATrashedOnesSchemaIsNotEdited"}),
        ("a trashed database is edited", DBS, '{ "no property $id" }.also { shell(it.databaseId) }', '{ "no property $id" }',
         ":data:desktopTest", {"aDatabaseKeepsOneViewAndATrashedOnesSchemaIsNotEdited"}),
        ("a cell moves page", TRIGGERS, 'PROPERTY_VALUE to listOf("page_id", "property_id"),', "",
         ":data:desktopTest", {"aCellStaysOnItsPageAndProperty"}),
    ],
    "12c": [
        ("an undone purge reads nothing again", FOLDER, "        if (undidPurge) {\n", "        if (false) {\n",
         ":data:desktopTest", {"aPurgeUndoneByALaterEditBringsBackWhatThePurgeTookOnThisDevice"}),
        ("a carried card is a person's move", CANVAS, 'if (n == id) s else automatic(s)', 's',
         ":data:desktopTest", {'aCardCarriedOrTidiedAfterItWasDeletedElsewhereStaysDeleted'}),
        ("a tidy is a person's move", CANVAS, 'store.put(requireNotNull(store.row(n)).edit(NODE_AT, automatic(s),', 'store.put(requireNotNull(store.row(n)).edit(NODE_AT, s,',
         ":data:desktopTest", {'aCardCarriedOrTidiedAfterItWasDeletedElsewhereStaysDeleted'}),
        ("a lift is a person's edit", CANVAS, 'edit(NODE_TREE, automatic(s), mapOf("parent_id" to lifted))', 'edit(NODE_TREE, s, mapOf("parent_id" to lifted))',
         ":data:desktopTest", {'aCardAndItsParentDeletedOnTwoDevicesBothStayDeleted'}),
        ("revive reads the app's stamps", PAGES, 'internal val Stamp.byHand get() = !device.endsWith("~")', 'internal val Stamp.byHand get() = true',
         ":data:desktopTest", {'aCardAndItsParentDeletedOnTwoDevicesBothStayDeleted'}),
        ('an edited card stays deleted', CANVAS, '            for (n in gone.values) latestByHand(n.edits())?.let { touch(n.id, it) }\n', '',
         ":data:desktopTest", {'deletingACardTakesItsLinesAndFramesLiftsItsChildrenAndALaterEditBringsThemAllBack'}),
        ('a line to a deleted card is lost', CANVAS, '                if (e.deletedAt == null || e.id in found) { touch(e.fromNodeId, newest); touch(e.toNodeId, newest) }\n', '',
         ":data:desktopTest", {'aLineOrAChildAddedToACardDeletedElsewhereBringsItBack'}),
        ('a child under a deleted card is lost', CANVAS, '            nodes.filter { it.deletedAt == null }.forEach { c -> Stamp(c.treeHlc, c.treeDevice).takeIf { it.byHand }?.let { s -> c.parentId?.let { touch(it, s) } } }\n', '',
         ":data:desktopTest", {'aLineOrAChildAddedToACardDeletedElsewhereBringsItBack'}),
        ('a revived card comes back alone', CANVAS, '                edges.filter { it.deletedAt != null && it.gone() == n.gone() && (it.fromNodeId in with || it.toNodeId in with) }.forEach { found[it.id] = it.gone() }\n', '',
         ":data:desktopTest", {'deletingACardTakesItsLinesAndFramesLiftsItsChildrenAndALaterEditBringsThemAllBack'}),
        ('lifted children stay lifted', CANVAS, '                nodes.filter { it.deletedAt == null && Stamp(it.treeHlc, it.treeDevice) == lift }.forEach { relift[it.id] = n.id to automatic(lift) }\n', '',
         ":data:desktopTest", {'deletingACardTakesItsLinesAndFramesLiftsItsChildrenAndALaterEditBringsThemAllBack'}),
        ('a frame keeps its lines', CANVAS, 'val going = (frames + id).toSet()', 'val going = setOf(id)',
         ":data:desktopTest", {'aFrameFollowingADeletedCardTakesItsLinesWithIt'}),
        ('a subtree stays behind', CANVAS, 'moves = (listOf(node) + carried(node, nodes))', 'moves = listOf(node)',
         ":data:desktopTest", {'movingACardCarriesItsSubtreeButNotItsFrames'}),
        ('a page not here yet reads deleted', PAGES, 'if (id in purged) PageState.DELETED else PageState.ABSENT', 'PageState.DELETED',
         ":data:desktopTest", {'aPageCardWhosePageIsNotHereYetIsNotADeletedPage'}),
        ('a canvas edit leaves the trash', PAGES, ' + board[p.id].orEmpty()', '',
         ":data:desktopTest", {'aCanvasEditAfterTheTrashBringsTheCanvasBack'}),
        ("a card's text clash is silent", PAGE, 'setOf(PAGE_TITLE, BLOCK_TEXT, CELL, NODE_TEXT, EDGE_LABEL)', 'setOf(PAGE_TITLE, BLOCK_TEXT, CELL, EDGE_LABEL)',
         ":data:desktopTest", {'aCardsTextAndALinesLabelChangedApartKeepTheEarlierInHistoryWithANotice'}),
        ('History forgets the canvas', PAGES, 'notice, cellsJson(cells, picksOf(pageId)), canvasJson(pageId)))', 'notice, cellsJson(cells, picksOf(pageId))))',
         ":data:desktopTest", {'historyGivesBackACanvasAsItWas'}),
        ('a line moves its ends', TRIGGERS, 'CANVAS_EDGE to listOf("page_id", "from_node_id", "to_node_id"),', '',
         ":data:desktopTest", {'aLineStaysBetweenTheCardsItWasDrawnBetween'}),
        ('frames draw over cards', CANVAS, 'compareBy({ it.type != NodeType.FRAME.name }, { it.zKey }, { it.id })', 'compareBy({ it.zKey }, { it.id })',
         ":data:desktopTest", {'framesAreDrawnFirstAndBringToFrontPutsACardOnTop'}),
    ],
    "12d": [
        ('opening a day takes a fresh stamp', JOURNAL, 'writes.merger.created(store, newPageRow(page, JOURNAL_STAMP, title, null, parent, "PAGE"))', 'writes.merger.created(store, newPageRow(page, clock.tick(), title, null, parent, "PAGE"))',
         ":data:desktopTest", {'openingADayTrashedElsewhereLeavesItInTheTrashAndWritingInItBringsItBack'}),
        ('today ignores the day boundary', JOURNAL, 'day(dayOf(now, personal.dayStart()))', 'day(now.date)',
         ":data:desktopTest", {'todayIsThePersonalDayAndARenamedDayStaysTheDay'}),
        ('a purged day stays purged', JOURNAL, '                if (page in purged) {\n', '                if (false) {\n',
         ":data:desktopTest", {'aDayDeletedForGoodAndOpenedAgainIsAPageEveryDeviceGets'}),
        ('a Road Map link stays on', RELS, 'targets.getValue(PAGE_RELATION).forEach { store.put(requireNotNull(store.row(it)).edit(GONE, s, mapOf("deleted_at" to s.hlc))) }', '',
         ":data:desktopTest", {'aRoadMapLinkIsOnePerPairCanBeTakenOffAndComesBackWhenMadeAgain'}),
        ('a Road Map link made again stays off', RELS, 'store.put(row.edit(GONE, s, mapOf("deleted_at" to null)))', 'Unit',
         ":data:desktopTest", {'aRoadMapLinkIsOnePerPairCanBeTakenOffAndComesBackWhenMadeAgain'}),
        ('links leave revive', PAGES, ' + linked[p.id].orEmpty()', '',
         ":data:desktopTest", {'aLinkMadeToAPageTrashedElsewhereBringsItBack'}),
        ('an unlink revives', PAGES, 'for (end in listOf(l.pageA, l.pageB)) linked.getOrPut(end) { mutableListOf() } += listOfNotNull(Stamp(l.madeHlc, l.madeDevice), Stamp(l.goneHlc, l.goneDevice).takeIf { l.deletedAt == null })', 'for (end in listOf(l.pageA, l.pageB)) linked.getOrPut(end) { mutableListOf() } += listOf(Stamp(l.madeHlc, l.madeDevice), Stamp(l.goneHlc, l.goneDevice))',
         ":data:desktopTest", {'aLinkTakenOffAfterATrashElsewhereLeavesThePageInTheTrash'}),
        ('blocked-by is no schema edit', PAGES, '            s.blockedHlc?.let { add(s.pageId, Stamp(it, requireNotNull(s.blockedDevice))) }\n', '',
         ":data:desktopTest", {'choosingWhatBlocksADatabaseTrashedElsewhereBringsItBack'}),
        ('a relation reads one side', DBS, 'val (row, other) = if (q.id == l.propertyId) l.pageId to l.targetId else l.targetId to l.pageId', 'val (row, other) = l.pageId to l.targetId',
         ":data:desktopTest", {'aRelationIsTwoColumnsReadingOneLinkAndLinksMadeApartBothStay'}),
        ('a dead pair holds the links', DBS, 'private fun stored(p: PropertyEntity, pairHere: Boolean) = if (pairHere) minOf(p.id, requireNotNull(p.pairPropertyId)) else p.id', 'private fun stored(p: PropertyEntity, pairHere: Boolean) = minOf(p.id, p.pairPropertyId ?: p.id)',
         ":data:desktopTest", {'aRelationColumnKeptAfterItsPairWasDeletedElsewhereStillLinks'}),
        ('a trashed blocker blocks', DBS, '.any { states[it] == PageState.LIVE }', '.any { states[it] != PageState.DELETED }',
         ":data:desktopTest", {'aRelationWithinOneDatabaseReadsEachWayInItsTwoColumnsAndSaysWhatBlocks'}),
        ("a relation outlives its pair's deletion", DBS, 'listOfNotNull(id, p.pairPropertyId?.takeIf { dao.properties(listOf(it)).isNotEmpty() })', 'listOf(id)',
         ":data:desktopTest", {'aRelationNeverChangesTypeAndGoesWithItsPair'}),
        ('a link to a page that is no row', DBS, '            require(targetId in members(requireNotNull(p.targetDatabaseId))) { "page $targetId is not a row of ${p.targetDatabaseId}" }\n', '',
         ":data:desktopTest", {'aRelationNeverChangesTypeAndGoesWithItsPair'}),
        ("a template's relation adds a column", TEMPL, 'newId().takeIf { !template }', 'newId()',
         ":data:desktopTest", {'aDatabaseTemplateCopiesItsSchemaViewsAndColourButNoRowsOrDoorway'}),
        ('a canvas copy loses its mind map', TEMPL, 'parentId = n.parentId?.let(ids::get)', 'parentId = null',
         ":data:desktopTest", {'aCanvasTemplateCopiesTheWholeBoardMindMapIncluded'}),
        ('templates are found', SEARCH, 'all { it.deletedAt == null && it.isTemplate != true }', 'all { it.deletedAt == null }',
         ":data:desktopTest", {'aTemplateIsNotFoundNorAParentAndATrashedOneIsInTheTrash'}),
        ('templates are in the tree', PAGES, 'it.deletedAt == null && it.isTemplate != true && shownUnder(it, pages) == parentId', 'it.deletedAt == null && shownUnder(it, pages) == parentId',
         ":data:desktopTest", {'aTemplateCopiesBlocksAndIsKeptOutOfTheTreeAndACopyIsIndependent'}),
        ('a journal hit has no date', SEARCH, '.title.ifBlank { journalDate(b.pageId)?.toString().orEmpty() }', '.title',
         ":data:desktopTest", {'aJournalDaysWritingIsFoundUnderItsDate'}),
    ],
    "s3a": [
        ('a formula stores names', DBS, 'if (same.size > 1) throw FormulaInputException("two properties are named \\"$n\\"", null); same.single()', 'null',
         ":data:desktopTest", {'aFormulaWrittenWithNamesKeepsWorkingWhenAPropertyIsRenamed'}),
        ('a rollup counts trashed rows', DBS, 'cells.getValue(relation.id).pages.filter { states[it] == PageState.LIVE }', 'cells.getValue(relation.id).pages.filter { true }',
         ":data:desktopTest", {'aRollupReadsTheLiveRelatedRowsOnly'}),
        ('a computed column sorts as text', DBS, 'compareValuesBy(a, b, { it.computedRank() }, { it.number }, { it.date }, { it.text?.lowercase() })', 'compareValues(a.text, b.text)',
         ":data:desktopTest", {'aComputedColumnOfNumbersAndTextSortsNumbersFirstAndEqualsReadsTextToo'}),
        ('an unticked box reads blank', DBS, 'PropertyType.CHECKBOX -> FormulaValue.Bool(cell?.checked == true)', 'PropertyType.CHECKBOX -> null',
         ":data:desktopTest", {'aFormulaReadsEachTypeAndAnotherFormulaAndAViewSortsAndFiltersOnIt'}),
        ('an edit may break a formula naming it', DBS, 'if (broken != null) throw', 'if (broken != null && false) throw',
         ":data:desktopTest", {'aFormulaNamingItselfIsACycleInNamesAndAnEditMayNotBreakAFormulaNamingIt'}),
        ('a cycle elsewhere turns checking off', DBS, ' ?: after.values.firstOrNull { it.errors.isNotEmpty() }?.errors.orEmpty().map { it.copy(position = -1) }', '.orEmpty()',
         ":data:desktopTest", {'aCycleASyncMadeLeavesNothingToCheckAgainstSoANewFormulaIsRefused'}),
        ('an error points into the stored text', DBS, 'e.position.takeIf { it >= 0 }?.let(typedAt)', 'e.position.takeIf { it >= 0 }',
         ":data:desktopTest", {'aFormulaReadsARollupAndAnErrorPointsAtWhatThePersonTyped'}),
        ('a position is not mapped back', FORMULA, 'return out.toString() to { at -> at - (shifts.lastOrNull { it.first <= at }?.second ?: 0) }', 'return out.toString() to { at -> at }',
         ":data:desktopTest", {'aFormulaReadsARollupAndAnErrorPointsAtWhatThePersonTyped'}),
        ('a formula reads no rollup', DBS, 'if (q.formula != null) formulaValue(q, cells, byId, parsed, memo, evaluating) else cell?.asValue()', 'if (q.formula != null) formulaValue(q, cells, byId, parsed, memo, evaluating) else null',
         ":data:desktopTest", {'aFormulaReadsARollupAndAnErrorPointsAtWhatThePersonTyped'}),
        ("a template copy keeps the source's keys", TEMPL, 'formula = p.formula?.let { f -> runCatching { rewriteKeys(f) { ids[it] } }.getOrDefault(f) },', 'formula = p.formula,',
         ":data:desktopTest", {'aComputedColumnNeverChangesTypeAndATemplateCopyKeepsItsFormulaWorking'}),
        ('a rollup reads a rollup', DBS, '                require(p.type != PropertyType.RELATION.name && (p.type != PropertyType.COMPUTED.name || p.formula != null)) { "a rollup reads a value, not a relation or another rollup" }\n', '',
         ":data:desktopTest", {'aRollupReadsNoRollupAndTwoDatabasesReadingEachOtherDoNotLoop'}),
        ('a text equal to a number never matches', DBS, 'if (cell.number != null && value.toDoubleOrNull() != null) value.toDouble() == cell.number else', 'if (value.toDoubleOrNull() != null) value.toDouble() == cell.number else',
         ":data:desktopTest", {'aComputedColumnOfNumbersAndTextSortsNumbersFirstAndEqualsReadsTextToo'}),
    ],
    "s3b": [
        ('a reset clears nothing', CHK, 'it.checked && Stamp(it.checkHlc, it.checkDevice) > reset', 'it.checked',
         ":data:desktopTest", {'aResetClearsATickMadeBeforeItEvenWhenTheTickSyncsAfter'}),
        ('a deleted list keeps its items', CHK, 'targets.getValue(CHECKLIST_ITEM).forEach { item ->', 'emptyList<String>().forEach { item ->',
         ":data:desktopTest", {'aDeleteWinsOverAnEditMadeApartAndARestoreBringsBackItsItems'}),
        ('a restore brings back items deleted by hand', CHK, 'it.deletedAt != null && !Stamp(it.goneHlc, it.goneDevice).byHand', 'it.deletedAt != null',
         ":data:desktopTest", {'anItemDeletedByHandComesBackFromTheTrashAndAListsRestoreTakesBackOnlyWhatItsDeletionTook'}),
        ("a list's deletion overrides one by hand", CHK, 'automatic(row.groups.getValue(GONE).stamp)', 'automatic(s)',
         ":data:desktopTest", {'anItemDeletedByHandComesBackFromTheTrashAndAListsRestoreTakesBackOnlyWhatItsDeletionTook'}),
        ('an item of a deleted list is edited', CHK, '{ "no item $id" }.also { live(it.checklistId) }', '{ "no item $id" }',
         ":data:desktopTest", {'anItemAddedElsewhereToAListDeletedHereIsNotFound'}),
        ('a new checklist goes last', CHK, 'keyBetween(null, dao.allChecklists().filter { it.deletedAt == null }.minOfOrNull { it.sortKey })', 'keyBetween(dao.allChecklists().filter { it.deletedAt == null }.maxOfOrNull { it.sortKey }, null)',
         ":data:desktopTest", {'aNewChecklistComesFirstAndListsAndItemsKeepTheirOrder'}),
        ('a blank item is taken', CHK, '.also { require(it.isNotEmpty()) { "an item needs text" } }', '',
         ":data:desktopTest", {'aNewChecklistComesFirstAndListsAndItemsKeepTheirOrder'}),
        ('an item under a deleted list is found', SEARCH, '.filter { it.deletedAt == null }.associateBy { it.id }', '.associateBy { it.id }',
         ":data:desktopTest", {'anItemAddedElsewhereToAListDeletedHereIsNotFound'}),
        ("a chart's day is the calendar's", CHART, 'val today = dayOf(now, dayStart)', 'val today = now.date',
         ":data:desktopTest", {'aChartShowsAnActivitysMinutesAndATrackersMeanPerPersonalDay'}),
        ('a day with no reading reads 0', CHART, 'days.map { d -> d to byDay[d]?.average() }', 'days.map { d -> d to (byDay[d]?.average() ?: 0.0) }',
         ":data:desktopTest", {'aChartShowsAnActivitysMinutesAndATrackersMeanPerPersonalDay'}),
        ('a source twice on a chart', CHART, '        require(sources.distinct().size == sources.size) { "a source is on a chart once" }\n', '',
         ":data:desktopTest", {'aNewChartComesFirstAndASourceIsOnAChartOnce'}),
        ("a week's goal is a day's", CHARTS, 'GoalPeriod.WEEK -> value / 7.0', 'GoalPeriod.WEEK -> value',
         ":core:desktopTest", {'aGoalIsADailyLine'}),
        ('a deleted chart stays', CHART, '{ s -> mapOf("deleted_at" to s.hlc) }\n\n    suspend fun restore', '{ mapOf("deleted_at" to null) }\n\n    suspend fun restore',
         ":data:desktopTest", {'sourcesAddedOnTwoDevicesBothStayAndADeleteWinsOverAnEdit'}),
    ],
}


def run(task):
    module = task.split(":")[1]
    results = "%s/build/test-results/desktopTest" % module
    shutil.rmtree(results, ignore_errors=True)
    with open("mutants.log", "w") as log:
        code = subprocess.call([GRADLEW, "--offline", task], stdout=log, stderr=log)
    failed = set()
    for xml in glob.glob(results + "/*.xml"):
        failed |= set(re.findall(r'testcase name="([^"\[]+)[^"]*"[^>]*>\s*<failure', open(xml, encoding="utf-8").read()))
    return code, failed


def main(slices):
    # Every pattern first: a stale one should stop the run before any build, not halfway through.
    for key in slices:
        for name, path, old, *_ in SLICES[key]:
            assert open(path, encoding="utf-8").read().count(old) == 1, "%s: pattern not found once in %s" % (name, path)
    survivors = []
    for key in slices:
        for name, path, old, new, task, expected in SLICES[key]:
            original = open(path, "rb").read()
            text = original.decode("utf-8")
            try:
                open(path, "wb").write(text.replace(old, new).encode("utf-8"))
                code, failed = run(task)
            finally:
                open(path, "wb").write(original)
            missed = expected - failed
            print("%-36s exit=%d failed: %s%s" % (name, code, ", ".join(sorted(failed)) or "NOTHING",
                                                  "  MISSED: " + ", ".join(sorted(missed)) if missed else ""))
            if missed:
                survivors.append(name)
    for task in sorted({m[4] for key in slices for m in SLICES[key]}):
        code, failed = run(task)
        print("%-36s exit=%d failures: %s" % ("control " + task, code, ", ".join(sorted(failed)) or "none"))
        assert code == 0 and not failed, "control must pass, or no kill above means anything"
    os.remove("mutants.log")
    assert not survivors, "survived: %s" % survivors


if __name__ == "__main__":
    main(sys.argv[1:] or sorted(SLICES))
