"""Slice 04: write ADR 04's expected occurrences, computed by the contest's reference model
(tools/recurrence_sim.py, the owner apps' verified rules), as a Kotlin test fixture, so the real
expander in :core is checked against the same truth the contest was scored on.

    python tools/recurrence_fixtures.py
Writes core/src/commonTest/kotlin/com/factotum/core/recurrence/RecurrenceTruth.kt.
Also writes seeded-draw vectors, computed here independently of the Kotlin port.
"""
import datetime as dt
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import recurrence_sim as rs  # noqa: E402

OUT = os.path.join(rs.ROOT, "core", "src", "commonTest", "kotlin", "com", "factotum", "core", "recurrence", "RecurrenceTruth.kt")
M64 = (1 << 64) - 1


def fnv1a64(s):
    h = 0xcbf29ce484222325
    for b in s.encode("utf-8"):
        h = ((h ^ b) * 0x100000001b3) & M64
    return h


def between(key, lo, hi):
    """The spike's SplitMix64 draw (tools/spikes/seeded_draw/Draw.java), reimplemented."""
    state, bound = fnv1a64(key), hi - lo
    highest = M64 - (M64 % bound)
    while True:
        state = (state + 0x9E3779B97F4A7C15) & M64
        z = state
        z = ((z ^ (z >> 30)) * 0xBF58476D1CE4E5B9) & M64
        z = ((z ^ (z >> 27)) * 0x94D049BB133111EB) & M64
        z = z ^ (z >> 31)
        if z <= highest:
            return lo + z % bound


def kt(t):
    return "LocalDateTime(%d, %d, %d, %d, %d)" % (t.year, t.month, t.day, t.hour, t.minute)


def case(cid):
    """The window and truth of one deterministic case, exactly as recurrence_sim.run_case compares them."""
    owner, truth, forms = rs.CASES[cid]
    start, until = rs.BOUNDS.get(cid, (rs.START, rs.HORIZON))
    if cid in ("tendril-second-tuesday", "mnemo-cron-dom-or-dow"):
        start = start.replace(hour=9, minute=0)
    if cid == "chronicle-weekdays":
        start = start.replace(hour=7, minute=30)
    if cid == "mnemo-cron-every-15":
        start = start.replace(hour=0, minute=0)
    want = [t for t in truth() if start <= t < until]
    if cid == "tendril-elastic-3d":
        until = rs.START + dt.timedelta(days=90)
        want = [t for t in want if t < until]
    if cid == "chronicle-every-90min":
        want = want[:40]
        until = want[-1] + dt.timedelta(minutes=1)
    form = forms["cron+ext"] if owner == "mnemo" else forms["rrule+ext"]
    return start, until, form, want


def main():
    rows = []
    for cid in rs.CASES:
        if rs.CASES[cid][1] is None:
            continue   # the random cases are property checks, written by hand in the test
        start, until, form, want = case(cid)
        kind = "cron" if rs.CASES[cid][0] == "mnemo" else "rrule"
        rows.append('        Truth("%s", "%s", "%s", %s, %s, listOf(%s)),' % (
            cid, kind, form, kt(start), kt(until), ", ".join(kt(t) for t in want)))
    keys = [("01JB8Z3K4Q7M2N5P6R8S9T0V1W|2026-10-05|RANDOM_DAYS", 2, 5), ("item|2026-10-05|RANDOM_WINDOW", 0, 120),
            ("01JB8Z3K4Q7M2N5P6R8S9T0V1X|2027-03-28|RANDOM_WINDOW", 0, 180), ("", 0, 4), ("é|1999-12-31|RANDOM_DAYS", 1, 100)]
    draws = "\n".join('        Draw("%s", %d, %d, %d),' % (k, lo, hi, between(k, lo, hi)) for k, lo, hi in keys)
    text = '''// Generated by tools/recurrence_fixtures.py from tools/recurrence_sim.py; do not edit.
package com.factotum.core.recurrence

import kotlinx.datetime.LocalDateTime

/** One ADR 04 case: its rule (RRULE text, or cron converted on read), the window, and the occurrences the owner app's rule gives. */
data class Truth(val id: String, val kind: String, val form: String, val start: LocalDateTime, val until: LocalDateTime, val expected: List<LocalDateTime>)

/** A seeded draw computed by the generator's own SplitMix64, to check the Kotlin port against. */
data class Draw(val key: String, val from: Int, val untilExclusive: Int, val value: Int)

val TRUTHS = listOf(
%s
)

val DRAWS = listOf(
%s
)
''' % ("\n".join(rows), draws)
    with open(OUT, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(text)
    print("wrote %d cases and %d draws to %s" % (len(rows), len(keys), OUT))


if __name__ == "__main__":
    main()
